
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - .

overrides:
  eslint-flat-config-utils: 3.0.1

allowBuilds:
  '@parcel/watcher': true
  '@vue-office/docx': true
  '@vue-office/excel': true
  '@vue-office/pptx': true
  core-js: true
  esbuild: true
  vue-demi: true
