/** 平台文件暂存 scene（与 edu-common FileUploadSceneKey 枚举逐值对齐，运行时真源） */
export enum FileUploadSceneKey {
  QUALITY_ACCREDITATION_EVIDENCE = 'QUALITY_ACCREDITATION_EVIDENCE',
  QUALITY_ANNUAL_REPORT_MATERIAL = 'QUALITY_ANNUAL_REPORT_MATERIAL',
  QUALITY_TRAINING_PLAN_FILE = 'QUALITY_TRAINING_PLAN_FILE',
  QUALITY_PROCESS_EVIDENCE = 'QUALITY_PROCESS_EVIDENCE',
  QUALITY_AI_TASK_MATERIAL = 'QUALITY_AI_TASK_MATERIAL',
  QUALITY_COURSE_SYLLABUS = 'QUALITY_COURSE_SYLLABUS',
  QUALITY_ARCHIVE_FILE = 'QUALITY_ARCHIVE_FILE',
  QUALITY_SCORE_IMPORT = 'QUALITY_SCORE_IMPORT',
  PORTFOLIO_MATERIAL = 'PORTFOLIO_MATERIAL',
  PORTFOLIO_EXCEL_IMPORT = 'PORTFOLIO_EXCEL_IMPORT',
  MARK_ARCHIVE_VOLUME_MATERIAL = 'MARK_ARCHIVE_VOLUME_MATERIAL',
  MARK_EXAM_TEMPLATE = 'MARK_EXAM_TEMPLATE',
  MARK_APPEAL_EVIDENCE = 'MARK_APPEAL_EVIDENCE',
  MARK_EXAM_SCAN_SOURCE = 'MARK_EXAM_SCAN_SOURCE',
  MARK_SCANNER_AGENT_RELEASE = 'MARK_SCANNER_AGENT_RELEASE',
  QUALITY_INDIRECT_RESPONSE_DOC = 'QUALITY_INDIRECT_RESPONSE_DOC',
}

/** 平台 Excel 导入 scene（与 edu-common ExcelImportSceneKey 枚举逐值对齐，运行时真源） */
export enum ExcelImportSceneKey {
  QUALITY_WORKGROUP_MEMBER = 'QUALITY_WORKGROUP_MEMBER',
  QUALITY_PROCESS_RECORD = 'QUALITY_PROCESS_RECORD',
  QUALITY_INDIRECT_RESPONSE = 'QUALITY_INDIRECT_RESPONSE',
  QUALITY_SCORE_BATCH = 'QUALITY_SCORE_BATCH',
  PORTFOLIO_EXTERNAL_TEACHER = 'PORTFOLIO_EXTERNAL_TEACHER',
  PORTFOLIO_DUAL_TEACHER = 'PORTFOLIO_DUAL_TEACHER',
  PORTFOLIO_INDICATOR_DEFINITION = 'PORTFOLIO_INDICATOR_DEFINITION',
  PORTFOLIO_DEVELOPMENT_PLAN_HISTORY = 'PORTFOLIO_DEVELOPMENT_PLAN_HISTORY',
  PORTFOLIO_DEVELOPMENT_RECORD = 'PORTFOLIO_DEVELOPMENT_RECORD',
  MARK_ARCHIVE_EXTERNAL = 'MARK_ARCHIVE_EXTERNAL',
  MARK_PAPER_ARCHIVE_HISTORY = 'MARK_PAPER_ARCHIVE_HISTORY',
  MARK_ROSTER_EXCEL = 'MARK_ROSTER_EXCEL',
}

const PORTFOLIO_SCENES = new Set<ExcelImportSceneKey>([
  ExcelImportSceneKey.PORTFOLIO_EXTERNAL_TEACHER,
  ExcelImportSceneKey.PORTFOLIO_DUAL_TEACHER,
  ExcelImportSceneKey.PORTFOLIO_INDICATOR_DEFINITION,
  ExcelImportSceneKey.PORTFOLIO_DEVELOPMENT_PLAN_HISTORY,
  ExcelImportSceneKey.PORTFOLIO_DEVELOPMENT_RECORD,
])

const MARK_SCENES = new Set<ExcelImportSceneKey>([
  // 课程考核 Excel 建卷 scene 已硬拒；仍路由到 mark 以便平台调用收到业务错误码
  ExcelImportSceneKey.MARK_ARCHIVE_EXTERNAL,
  ExcelImportSceneKey.MARK_PAPER_ARCHIVE_HISTORY,
  ExcelImportSceneKey.MARK_ROSTER_EXCEL,
])

/** 解析 Excel 导入 API 前缀 */
export function resolveExcelImportApiBase(sceneKey: ExcelImportSceneKey): string {
  if (PORTFOLIO_SCENES.has(sceneKey)) {
    return '/api/portfolio/platform/excel-import'
  }
  if (MARK_SCENES.has(sceneKey)) {
    return '/api/mark/platform/excel-import'
  }
  return '/api/quality/platform/excel-import'
}

/** Excel scene 对应的文件暂存 scene */
export function resolveFileStageSceneForExcel(sceneKey: ExcelImportSceneKey): FileUploadSceneKey {
  if (sceneKey.startsWith('PORTFOLIO_') || sceneKey.startsWith('MARK_')) {
    return FileUploadSceneKey.PORTFOLIO_EXCEL_IMPORT
  }
  return FileUploadSceneKey.QUALITY_SCORE_IMPORT
}
