/**
 * 考试详情工作台路由（独立全屏 layout，对标 web-vue practice-detail-layout）
 *
 * 路径：/teacher/exam-workspace/:examId/*
 * 不在 TeacherLayout 内，进入后隐藏全局侧栏，使用考试专属侧栏菜单。
 */
import type { RouteMeta, RouteRecordRaw } from 'vue-router'
import { RoleEnum } from '@/utils/permission'

const TEACHER_ROLES = [RoleEnum.SCH_TECH]

/**
 * 考试工作台子路由 meta：journeyKey 与 markStageKey 必填。
 *
 * journeyKey 是「该路由属于哪一步教师旅程」的单一可信来源（Vue Router 官方设计：
 * 路由固有属性写在 meta 上）。设为必填后，任何新增 workspace 子路由若遗漏 journeyKey，
 * 在 tsc 阶段即报错，无需运行时反查菜单或 markStageKey 兜底。
 */
type WorkspaceChildMeta
  = & Omit<RouteMeta, 'journeyKey' | 'markStageKey'>
    & Required<Pick<RouteMeta, 'journeyKey' | 'markStageKey'>>
    & {
      /** 子页已自带 StageWorkbenchShell / ExamWorkspacePageShell 时置 true，避免布局重复包裹 */
      hasWorkbenchShell?: boolean
    }

function workspaceChild(
  path: string,
  name: string,
  component: () => Promise<unknown>,
  meta: WorkspaceChildMeta,
): RouteRecordRaw {
  return {
    path,
    name,
    component,
    meta: {
      roles: TEACHER_ROLES,
      hideInMenu: true,
      layout: 'ExamWorkspace',
      requiresAuth: true,
      ...meta,
    },
  }
}

export const examWorkspaceRoutes: RouteRecordRaw = {
  path: '/teacher/exam-workspace/:examId',
  name: 'TeacherExamWorkspace',
  component: () => import('@/views/teacher/exam-workspace-layout.vue'),
  redirect: (to) => ({
    name: 'TeacherExamWorkspaceOverview',
    params: { examId: to.params.examId },
  }),
  meta: {
    title: '考试工作台',
    roles: TEACHER_ROLES,
    hideInMenu: true,
    layout: 'ExamWorkspace',
    requiresAuth: true,
  },
  children: [
    workspaceChild('overview', 'TeacherExamWorkspaceOverview', () => import('@/views/teacher/exam-detail.vue'), {
      title: '考试概览',
      markStageKey: 'EXAM_PREP',
      journeyKey: 'overview',
      workspacePhase: 'overview',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('prep', 'TeacherExamWorkspacePrep', () => import('@/views/teacher/exam-prep-workbench.vue'), {
      title: '考试准备',
      markStageKey: 'EXAM_PREP',
      journeyKey: 'prep',
      workspacePhase: 'prep',
      keepAlive: false,
      hasWorkbenchShell: true,
    }),
    workspaceChild('print-package', 'TeacherExamWorkspacePrintPackage', () => import('@/views/teacher/print-package.vue'), {
      title: '印刷包管理',
      markStageKey: 'EXAM_PREP',
      journeyKey: 'prep',
      workspacePhase: 'prep',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('layout-designer', 'TeacherExamWorkspaceLayoutDesigner', () => import('@/views/teacher/exam-layout-designer.vue'), {
      title: '制卷设计',
      markStageKey: 'PAPER_TEMPLATE',
      journeyKey: 'prep',
      workspacePhase: 'layout-designer',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('candidate-roster', 'TeacherExamWorkspaceCandidateRoster', () => import('@/views/teacher/candidate-roster.vue'), {
      title: '考生名册',
      markStageKey: 'CANDIDATE_ROSTER',
      journeyKey: 'prep',
      workspacePhase: 'candidate-roster',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/batches', 'TeacherExamWorkspaceScanBatches', () => import('@/views/teacher/scan-batch-workbench.vue'), {
      title: '扫描批次',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/batches/:scanBatchId', 'TeacherExamWorkspaceScanBatchDetail', () => import('@/views/teacher/scan-batch-detail-workbench.vue'), {
      title: '批次详情',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
      layoutWide: true,
    }),
    workspaceChild('scan/manual-entry', 'TeacherExamWorkspaceScanManualEntry', () => import('@/views/teacher/scan-manual-entry.vue'), {
      title: '手动补录',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: false,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/monitor', 'TeacherExamWorkspaceScanMonitor', () => import('@/views/teacher/scan-live-monitor.vue'), {
      title: '扫描监控',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/ledger', 'TeacherExamWorkspaceScanLedger', () => import('@/views/teacher/image-ledger.vue'), {
      title: '影像账本',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/devices', 'TeacherExamWorkspaceScanDevices', () => import('@/views/teacher/printer-management.vue'), {
      title: '扫描设备',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/ocr', 'TeacherExamWorkspaceScanOcr', () => import('@/views/teacher/ocr-settings.vue'), {
      title: 'OCR 配置',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('scan/ops', 'TeacherExamWorkspaceScanOps', () => import('@/views/teacher/exam-scan-ops.vue'), {
      title: '扫描运营',
      markStageKey: 'SCAN',
      journeyKey: 'scan',
      workspacePhase: 'scan',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org', 'TeacherExamWorkspaceMarkingOrg', () => import('@/views/admin/marking-organization/marking-org-entry.vue'), {
      title: '阅卷组织',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/trial', 'TeacherExamWorkspaceMarkingOrgTrialHub', () => import('@/views/admin/marking-organization/marking-org-session-hub.vue'), {
      title: '试评定标',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      sessionPhase: 'trial',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/formal', 'TeacherExamWorkspaceMarkingOrgFormalHub', () => import('@/views/admin/marking-organization/marking-org-session-hub.vue'), {
      title: '正评会话',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      sessionPhase: 'formal',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/:organizationId', 'TeacherExamWorkspaceMarkingOrgDetail', () => import('@/views/admin/marking-organization/detail.vue'), {
      title: '组织详情',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/:organizationId/trial-sessions', 'TeacherExamWorkspaceMarkingOrgTrialSessions', () => import('@/views/admin/marking-organization/trial-sessions.vue'), {
      title: '试评定标',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/:organizationId/formal-sessions', 'TeacherExamWorkspaceMarkingOrgFormalSessions', () => import('@/views/admin/marking-organization/formal-sessions.vue'), {
      title: '正评会话',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking-org/:organizationId/sessions', 'TeacherExamWorkspaceMarkingOrgSessions', () => import('@/views/admin/marking-organization/sessions.vue'), {
      title: '试评 / 正评',
      markStageKey: 'MARKING_ORG',
      journeyKey: 'assign',
      workspacePhase: 'marking-org',
      keepAlive: false,
      noCache: true,
      hasWorkbenchShell: true,
      hideInMenu: true,
    }),
    workspaceChild('trial/task-pool', 'TeacherExamWorkspaceTrialTaskPool', () => import('@/views/teacher/marking-task-pool.vue'), {
      title: '试评任务池',
      markStageKey: 'TRIAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'trial',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('trial/progress', 'TeacherExamWorkspaceTrialProgress', () => import('@/views/teacher/exam-workspace/marking-progress-dashboard.vue'), {
      title: '试评进度',
      markStageKey: 'TRIAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'trial',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/review-batch', 'TeacherExamWorkspaceReviewBatchConfirm', () => import('@/views/teacher/review-batch-confirm.vue'), {
      title: '批量复核确认',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/experience-assist-policy', 'TeacherExamWorkspaceMarkingExperienceAssistPolicy', () => import('@/views/teacher/exam-workspace/marking-experience-assist-policy.vue'), {
      title: '经验辅助评阅',
      markStageKey: 'EXAM_PREP',
      journeyKey: 'prep',
      workspacePhase: 'prep',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/task-pool', 'TeacherExamWorkspaceMarkingTaskPool', () => import('@/views/teacher/marking-task-pool.vue'), {
      title: '阅卷任务池',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/task/:taskId', 'TeacherExamWorkspaceMarkingTaskDetail', () => import('@/views/teacher/marking-task-detail.vue'), {
      title: '阅卷工作台',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      layoutWide: true,
      keepAlive: false,
      noCache: true,
    }),
    workspaceChild('marking/progress', 'TeacherExamWorkspaceMarkingProgress', () => import('@/views/teacher/exam-workspace/marking-progress-dashboard.vue'), {
      title: '进度看板',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/review-progress', 'TeacherExamWorkspaceMarkingReviewProgress', () => import('@/views/teacher/review-progress.vue'), {
      title: 'OCR/AI 复核进度',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/arbitration', 'TeacherExamWorkspaceMarkingArbitration', () => import('@/views/teacher/review-arbitration.vue'), {
      title: '仲裁裁定',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/quality', 'TeacherExamWorkspaceMarkingQuality', () => import('@/views/teacher/marking-spot-check.vue'), {
      title: '抽检处理',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/quality-monitor', 'TeacherExamWorkspaceMarkingQualityMonitor', () => import('@/views/admin/marking-quality-dashboard.vue'), {
      title: '阅卷质量监控',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/audit-trail', 'TeacherExamWorkspaceMarkingAuditTrail', () => import('@/views/admin/audit-trail.vue'), {
      title: '批改审计',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/review', 'TeacherExamWorkspaceMarkingReview', () => import('@/views/teacher/review-workspace.vue'), {
      title: 'OCR/AI 复核',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('marking/review/:taskId', 'TeacherExamWorkspaceReviewWorkspace', () => import('@/views/teacher/review-workspace.vue'), {
      title: 'OCR/AI 单题复核',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      layoutWide: true,
      keepAlive: false,
      noCache: true,
    }),
    workspaceChild('marking/review/:taskId/detail', 'TeacherExamWorkspaceReviewTaskDetail', () => import('@/views/teacher/review-task-detail.vue'), {
      title: '复核任务详情',
      markStageKey: 'FORMAL_MARKING',
      journeyKey: 'mark',
      workspacePhase: 'marking',
      layoutWide: true,
      keepAlive: false,
      noCache: true,
    }),
    workspaceChild('score/summary', 'TeacherExamWorkspaceScoreSummary', () => import('@/views/teacher/score-finalize.vue'), {
      title: '成绩确认与发布',
      markStageKey: 'SCORE_PUBLISH',
      journeyKey: 'publish',
      workspacePhase: 'score',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    {
      path: 'score/release',
      name: 'TeacherExamWorkspaceScoreRelease',
      redirect: (to) => ({
        name: 'TeacherExamWorkspaceScoreSummary',
        params: { examId: to.params.examId },
        query: to.query,
      }),
      meta: {
        title: '成绩确认与发布',
        roles: TEACHER_ROLES,
        hideInMenu: true,
        layout: 'ExamWorkspace',
        requiresAuth: true,
        markStageKey: 'SCORE_PUBLISH',
        journeyKey: 'publish',
        workspacePhase: 'score',
      },
    },
    workspaceChild('score/absence', 'TeacherExamWorkspaceScoreAbsence', () => import('@/views/teacher/absence-confirm.vue'), {
      title: '缺考确认',
      markStageKey: 'SCORE_PUBLISH',
      journeyKey: 'publish',
      workspacePhase: 'score',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('score/appeal', 'TeacherExamWorkspaceScoreAppeal', () => import('@/views/teacher/appeal-handle.vue'), {
      title: '复核申诉',
      markStageKey: 'SCORE_PUBLISH',
      journeyKey: 'publish',
      workspacePhase: 'score',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/package', 'TeacherExamWorkspaceArchivePackage', () => import('@/views/teacher/archive-volume/archive-volume-exam-progress.vue'), {
      title: '归档复盘',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/ai-analysis', 'TeacherExamWorkspaceArchiveAiAnalysis', () => import('@/views/teacher/exam-workspace/exam-workspace-ai-analysis.vue'), {
      title: 'AI 分析',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/question-analysis', 'TeacherExamWorkspaceArchiveQuestionAnalysis', () => import('@/views/teacher/exam-workspace/exam-workspace-question-analysis.vue'), {
      title: '题目分析',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/statistics', 'TeacherExamWorkspaceArchiveStatistics', () => import('@/views/teacher/statistics.vue'), {
      title: '成绩统计',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/grading-experience', 'TeacherExamWorkspaceGradingExperience', () => import('@/views/teacher/grading-experience-hub.vue'), {
      title: '阅卷经验库',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/exports', 'TeacherExamWorkspaceArchiveExports', () => import('@/views/common/exam-export-tasks.vue'), {
      title: '导出任务',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
    workspaceChild('archive/teaching-affairs', 'TeacherExamWorkspaceArchiveTeachingAffairs', () => import('@/views/admin/teaching-affairs-sync.vue'), {
      title: '教务同步',
      markStageKey: 'ARCHIVE',
      journeyKey: 'archive',
      workspacePhase: 'archive',
      keepAlive: true,
      hasWorkbenchShell: true,
    }),
  ],
}
