/**
 * 教学档案袋（edu-quality 标准包）前端路由
 * 与质量评价 /quality 平级，独立 Layout 域；API 前缀 /api/portfolio/*
 */
import type { RouteRecordRaw } from 'vue-router'
import type { PortfolioWorkShellCode } from '@/apis/portfolio/types'
import { RoleEnum } from '@/utils/permission'
import { PORTFOLIO_ROUTE_PREFIX } from '@/utils/portfolio-route'

const TEACHER_ROLES = [RoleEnum.SCH_TECH]
const ALL_ROLES = [RoleEnum.SUPER_ADMIN, ...TEACHER_ROLES]

/** 档案袋组织管理：超管或 edu-user 判定的租户管理员 */
const PORTFOLIO_ADMIN_ROUTE_META = {
  roles: [RoleEnum.SUPER_ADMIN, RoleEnum.SCH_TECH],
  requireTenantAdmin: true,
}

const PORTFOLIO_TEACHER_MENU_GROUP = 'portfolio-teacher'
const TEACHER_WORK_SHELLS: PortfolioWorkShellCode[] = ['TEACHER']
const DEPARTMENT_REVIEW_WORK_SHELLS: PortfolioWorkShellCode[] = ['DEPARTMENT_REVIEW']
const SCHOOL_GOVERNANCE_WORK_SHELLS: PortfolioWorkShellCode[] = ['SCHOOL_GOVERNANCE']
const CONFIGURATION_WORK_SHELLS: PortfolioWorkShellCode[] = ['CONFIGURATION']
const EXTERNAL_EXPERT_WORK_SHELLS: PortfolioWorkShellCode[] = ['EXTERNAL_EXPERT']
/** 专家深链审阅/填报：专家壳 + 学校治理（授权管理预览） */
const EXPERT_REVIEW_WORK_SHELLS: PortfolioWorkShellCode[] = ['EXTERNAL_EXPERT', 'SCHOOL_GOVERNANCE']

const portfolioTeacherMenuMeta = {
  menuGroup: PORTFOLIO_TEACHER_MENU_GROUP,
  menuGroupTitle: '教师自助',
  menuGroupIcon: 'user',
  menuGroupOrder: 1,
  portfolioWorkShells: TEACHER_WORK_SHELLS,
}

const PORTFOLIO_ORG_MENU_GROUP = 'portfolio-org'
const portfolioOrgMenuMeta = {
  menuGroup: PORTFOLIO_ORG_MENU_GROUP,
  menuGroupTitle: '组织与模板',
  menuGroupIcon: 'apartment',
  menuGroupOrder: 2,
  portfolioWorkShells: CONFIGURATION_WORK_SHELLS,
}

const PORTFOLIO_DEPARTMENT_MENU_GROUP = 'portfolio-department'
const portfolioDepartmentMenuMeta = {
  menuGroup: PORTFOLIO_DEPARTMENT_MENU_GROUP,
  menuGroupTitle: '院系审核',
  menuGroupIcon: 'audit',
  menuGroupOrder: 1,
  portfolioWorkShells: DEPARTMENT_REVIEW_WORK_SHELLS,
}

const PORTFOLIO_DUAL_TEACHER_MENU_GROUP = 'portfolio-dual-teacher'
const portfolioDualTeacherMenuMeta = {
  menuGroup: PORTFOLIO_DUAL_TEACHER_MENU_GROUP,
  menuGroupTitle: '双师管理',
  menuGroupIcon: 'team',
  menuGroupOrder: 3,
  portfolioWorkShells: SCHOOL_GOVERNANCE_WORK_SHELLS,
}

/** 侧栏「发展指标」分组 */
const INDICATOR_MENU_GROUP = 'portfolio-indicator'
const indicatorMenuMeta = {
  menuGroup: INDICATOR_MENU_GROUP,
  menuGroupTitle: '发展指标',
  menuGroupIcon: 'bar-chart',
  menuGroupOrder: 4,
  portfolioWorkShells: CONFIGURATION_WORK_SHELLS,
}

const PORTFOLIO_EVALUATION_MENU_GROUP = 'portfolio-evaluation'
const portfolioEvaluationMenuMeta = {
  menuGroup: PORTFOLIO_EVALUATION_MENU_GROUP,
  menuGroupTitle: '多元评价',
  menuGroupIcon: 'form',
  menuGroupOrder: 5,
  portfolioWorkShells: SCHOOL_GOVERNANCE_WORK_SHELLS,
}

const PORTFOLIO_RESOURCE_MENU_GROUP = 'portfolio-resource'
const portfolioResourceMenuMeta = {
  menuGroup: PORTFOLIO_RESOURCE_MENU_GROUP,
  menuGroupTitle: '专项资源库',
  menuGroupIcon: 'database',
  menuGroupOrder: 7,
  portfolioWorkShells: SCHOOL_GOVERNANCE_WORK_SHELLS,
}

const PORTFOLIO_GOVERNANCE_MENU_GROUP = 'portfolio-governance'
const portfolioGovernanceMenuMeta = {
  menuGroup: PORTFOLIO_GOVERNANCE_MENU_GROUP,
  menuGroupTitle: '专项治理',
  menuGroupIcon: 'control',
  menuGroupOrder: 6,
  portfolioWorkShells: SCHOOL_GOVERNANCE_WORK_SHELLS,
}

const PORTFOLIO_ANALYTICS_MENU_GROUP = 'portfolio-analytics'
const portfolioAnalyticsMenuMeta = {
  menuGroup: PORTFOLIO_ANALYTICS_MENU_GROUP,
  menuGroupTitle: '师资分析',
  menuGroupIcon: 'bar-chart',
  menuGroupOrder: 8,
  portfolioWorkShells: SCHOOL_GOVERNANCE_WORK_SHELLS,
}

const PORTFOLIO_SECURITY_MENU_GROUP = 'portfolio-security'
const portfolioSecurityMenuMeta = {
  menuGroup: PORTFOLIO_SECURITY_MENU_GROUP,
  menuGroupTitle: '权限与审计',
  menuGroupIcon: 'safety',
  menuGroupOrder: 9,
  portfolioWorkShells: CONFIGURATION_WORK_SHELLS,
}

/** 侧栏次要入口：默认收进分组「更多」 */
const MENU_SECONDARY = { menuTier: 'secondary' as const }

export const portfolioRoutes: RouteRecordRaw[] = [
  {
    path: PORTFOLIO_ROUTE_PREFIX,
    name: 'PortfolioLayout',
    component: () => import('@/layout/index.vue'),
    redirect: `${PORTFOLIO_ROUTE_PREFIX}/entry`,
    meta: {
      title: '教学档案袋',
      roles: ALL_ROLES,
      icon: 'folder',
      hideInMenu: true,
    },
    children: [
      {
        path: 'entry',
        name: 'PortfolioWorkShellEntry',
        component: () => import('@/views/portfolio/work-shell-entry.vue'),
        meta: {
          title: '教学档案袋',
          roles: ALL_ROLES,
          hideInMenu: true,
        },
      },
      {
        path: 'scan-ops',
        name: 'PortfolioScanOps',
        component: () => import('@/views/portfolio/portfolio-scan-ops.vue'),
        meta: {
          title: '档案袋扫描运营',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'scan',
          hideInMenu: true,
          keepAlive: true,
        },
      },
      {
        path: 'teacher/home',
        name: 'PortfolioTeacherHome',
        component: () => import('@/views/portfolio/teacher-home.vue'),
        meta: {
          title: '我的工作台',
          roles: ALL_ROLES,
          icon: 'home',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/masterpiece',
        name: 'PortfolioTeacherMasterpiece',
        component: () => import('@/views/portfolio/teacher-masterpiece.vue'),
        meta: {
          title: '教学代表作',
          roles: ALL_ROLES,
          icon: 'file-text',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/process-journal',
        name: 'PortfolioTeacherProcessJournal',
        component: () => import('@/views/portfolio/teacher-process-journal.vue'),
        meta: {
          title: '过程记录',
          roles: ALL_ROLES,
          icon: 'form',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/onboarding',
        name: 'PortfolioTeacherOnboarding',
        component: () => import('@/views/portfolio/teacher-onboarding.vue'),
        meta: {
          title: '认识档案',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/privacy-consent',
        name: 'PortfolioTeacherPrivacyConsent',
        component: () => import('@/views/portfolio/teacher-privacy-consent.vue'),
        meta: {
          title: '个人信息处理同意',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/intake',
        name: 'PortfolioTeacherIntake',
        component: () => import('@/views/portfolio/teacher-intake.vue'),
        meta: {
          title: '材料采集',
          roles: ALL_ROLES,
          icon: 'cloud-upload',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/review-status',
        name: 'PortfolioTeacherReviewStatus',
        component: () => import('@/views/portfolio/teacher-review-status.vue'),
        meta: {
          title: '审核进度',
          roles: ALL_ROLES,
          icon: 'audit',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/export-approval',
        name: 'PortfolioExportApprovalMine',
        component: () => import('@/views/portfolio/export-approval-mine.vue'),
        meta: {
          title: '我的导出申请',
          roles: ALL_ROLES,
          icon: 'download',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'scene/promotion',
        name: 'PortfolioPromotionScene',
        component: () => import('@/views/portfolio/promotion-scene.vue'),
        meta: {
          title: '职称材料包',
          roles: ALL_ROLES,
          icon: 'file-protect',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'scene/dual-teacher',
        name: 'PortfolioDualTeacherScene',
        component: () => import('@/views/portfolio/dual-teacher-apply.vue'),
        meta: {
          title: '资格与认定',
          roles: ALL_ROLES,
          icon: 'safety-certificate',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'scene/annual-review',
        name: 'PortfolioAnnualReviewScene',
        component: () => import('@/views/portfolio/annual-review-scene.vue'),
        meta: {
          title: '年度考核',
          roles: ALL_ROLES,
          icon: 'calendar',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/policy-library',
        name: 'PortfolioPolicyLibraryBrowse',
        component: () => import('@/views/portfolio/policy-library-browse.vue'),
        meta: {
          title: '政策检索',
          roles: ALL_ROLES,
          icon: 'book',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/portrait',
        name: 'PortfolioTeacherPortrait',
        component: () => import('@/views/portfolio/teacher-portrait.vue'),
        meta: {
          title: '教师画像',
          roles: ALL_ROLES,
          icon: 'radar-chart',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/gap/:taskId',
        name: 'PortfolioTeacherGap',
        component: () => import('@/views/portfolio/teacher-gap.vue'),
        meta: {
          title: '补采任务',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/archive/:categoryId',
        name: 'PortfolioArchiveCategoryEdit',
        component: () => import('@/views/portfolio/archive-category-edit.vue'),
        meta: {
          title: '分类填报',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/correction',
        name: 'PortfolioTeacherCorrection',
        component: () => import('@/views/portfolio/correction.vue'),
        meta: {
          title: '我的纠错',
          roles: ALL_ROLES,
          icon: 'exception',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/evaluation',
        name: 'PortfolioTeacherEvaluation',
        component: () => import('@/views/portfolio/teacher-evaluation.vue'),
        meta: {
          title: '我的评价',
          roles: ALL_ROLES,
          icon: 'form',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/materials',
        redirect: to => ({
          path: '/portfolio/teacher/intake',
          query: to.query,
        }),
      },
      {
        path: 'teacher/materials-legacy',
        name: 'PortfolioTeacherMaterials',
        component: () => import('@/views/portfolio/teacher-materials.vue'),
        meta: {
          title: '材料库',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/archive',
        name: 'PortfolioTeacherArchive',
        component: () => import('@/views/portfolio/teacher-archive.vue'),
        meta: {
          title: '我的档案',
          roles: ALL_ROLES,
          icon: 'profile',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/profile',
        name: 'PortfolioTeacherProfile',
        component: () => import('@/views/portfolio/teacher-profile.vue'),
        meta: {
          title: '个人资料',
          roles: ALL_ROLES,
          icon: 'user',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/philosophy',
        name: 'PortfolioTeacherTeachingPhilosophy',
        component: () => import('@/views/portfolio/teacher-teaching-philosophy.vue'),
        meta: {
          title: '教学理念',
          roles: ALL_ROLES,
          icon: 'edit',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/course-archive',
        name: 'PortfolioTeacherCourseArchive',
        component: () => import('@/views/portfolio/teacher-course-archive.vue'),
        meta: {
          title: '课程档案',
          roles: ALL_ROLES,
          icon: 'book',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/honor',
        name: 'PortfolioTeacherHonor',
        component: () => import('@/views/portfolio/teacher-honor.vue'),
        meta: {
          title: '获奖情况',
          roles: ALL_ROLES,
          icon: 'trophy',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/extension-activity',
        name: 'PortfolioTeacherExtensionActivity',
        component: () => import('@/views/portfolio/teacher-extension-activity.vue'),
        meta: {
          title: '教学拓展活动',
          roles: ALL_ROLES,
          icon: 'calendar',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'org',
        name: 'PortfolioOrgAdmin',
        component: () => import('@/views/portfolio/org-admin.vue'),
        meta: {
          title: '档案袋组织',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'apartment',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/configuration',
        name: 'PortfolioConfigurationWorkbench',
        component: () => import('@/views/portfolio/configuration-workbench.vue'),
        meta: {
          title: '档案袋配置中心',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'setting',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/integration',
        name: 'PortfolioIntegrationDashboard',
        component: () => import('@/views/portfolio/integration-dashboard.vue'),
        meta: {
          title: '数据集成中心',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'cloud-sync',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/major-group-portfolio',
        name: 'PortfolioMajorGroupPortfolio',
        component: () => import('@/views/portfolio/major-group-portfolio.vue'),
        meta: {
          title: '专业群档案袋',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'cluster',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'admin/export-approval',
        name: 'PortfolioExportApprovalAdmin',
        component: () => import('@/views/portfolio/export-approval-admin.vue'),
        meta: {
          title: '导出审批',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'safety-certificate',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioSecurityMenuMeta,
        },
      },
      {
        path: 'admin/mask-rule',
        name: 'PortfolioMaskRuleAdmin',
        component: () => import('@/views/portfolio/mask-rule-admin.vue'),
        meta: {
          title: '脱敏规则',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'eye-invisible',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioSecurityMenuMeta,
        },
      },
      {
        path: 'admin/audit-log',
        name: 'PortfolioAuditLogAdmin',
        component: () => import('@/views/portfolio/audit-log-admin.vue'),
        meta: {
          title: '审计日志',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'file-search',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioSecurityMenuMeta,
        },
      },
      {
        path: 'school/policy-library',
        name: 'PortfolioPolicyLibraryAdmin',
        component: () => import('@/views/portfolio/policy-library-admin.vue'),
        meta: {
          title: '政策文件库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'book',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/template',
        name: 'PortfolioTemplateAdmin',
        component: () => import('@/views/portfolio/template-admin.vue'),
        meta: {
          title: '档案模板配置',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'file-protect',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/archive-score-rule',
        name: 'PortfolioArchiveScoreRuleAdmin',
        component: () => import('@/views/portfolio/archive-score-rule-admin.vue'),
        meta: {
          title: '档案评分规则',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'calculator',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'teachers',
        name: 'PortfolioTeacherDirectory',
        component: () => import('@/views/portfolio/teacher-directory.vue'),
        meta: {
          title: '教师名册',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'team',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'teacher-lifecycle',
        name: 'PortfolioTeacherLifecycleAdmin',
        component: () => import('@/views/portfolio/teacher-lifecycle-admin.vue'),
        meta: {
          title: '教师生命周期',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'swap',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'ai-candidate-confirm',
        redirect: to => {
          const query = { ...to.query }
          if (typeof query.taskId === 'string') {
            return { path: '/portfolio/teacher/intake', query }
          }
          return { path: '/portfolio/teacher/intake', query }
        },
      },
      {
        path: 'ai-candidate-confirm-legacy',
        name: 'PortfolioAiCandidateConfirm',
        redirect: to => ({
          path: '/portfolio/teacher/intake',
          query: { ...to.query },
        }),
        meta: {
          title: 'AI 候选字段确认',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'teacher/ai-assistants',
        name: 'PortfolioAiFourAssistants',
        component: () => import('@/views/portfolio/ai-four-assistants.vue'),
        meta: {
          title: 'AI 四类助手',
          roles: ALL_ROLES,
          icon: 'bulb',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'ai-orchestration',
        name: 'PortfolioAiOrchestration',
        component: () => import('@/views/portfolio/ai-orchestration.vue'),
        meta: {
          title: 'AI 问数与政策核验',
          roles: ALL_ROLES,
          icon: 'message',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'department/review',
        name: 'PortfolioDepartmentReview',
        component: () => import('@/views/portfolio/department-review.vue'),
        meta: {
          title: '院系审核台',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'audit',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/reviewer-browse',
        name: 'PortfolioReviewerBrowse',
        component: () => import('@/views/portfolio/reviewer-browse.vue'),
        meta: {
          title: '档案浏览',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'read',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/gap',
        name: 'PortfolioDepartmentGap',
        component: () => import('@/views/portfolio/department-gap.vue'),
        meta: {
          title: '补采督办',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'alert',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/objection',
        name: 'PortfolioDepartmentObjection',
        component: () => import('@/views/portfolio/department-objection.vue'),
        meta: {
          title: '公示异议',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'message',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/title-promotion-review',
        name: 'PortfolioDepartmentTitlePromotionReview',
        component: () => import('@/views/portfolio/title-promotion-admin.vue'),
        meta: {
          title: '职称申报院审',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'solution',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/dual-teacher-review',
        name: 'PortfolioDepartmentDualTeacherReview',
        component: () => import('@/views/portfolio/dual-teacher-admin.vue'),
        meta: {
          title: '双师认定院审',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'team',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'school/evaluation',
        name: 'PortfolioSchoolEvaluation',
        component: () => import('@/views/portfolio/school-evaluation.vue'),
        meta: {
          title: '学校评价',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'audit',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioEvaluationMenuMeta,
        },
      },
      {
        path: 'school/double-high/tasks',
        name: 'PortfolioDoubleHighTasks',
        component: () => import('@/views/portfolio/shuanggao-tasks.vue'),
        meta: {
          title: '双高任务台账',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'schedule',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/double-high/monitor',
        name: 'PortfolioDoubleHighMonitor',
        component: () => import('@/views/portfolio/shuanggao-monitor.vue'),
        meta: {
          title: '双高建设监测',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'line-chart',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/title-promotion',
        name: 'PortfolioTitlePromotionAdmin',
        component: () => import('@/views/portfolio/title-promotion-admin.vue'),
        meta: {
          title: '职称申报治理',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'solution',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/title-criteria-templates',
        name: 'PortfolioTitleCriteriaTemplates',
        component: () => import('@/views/portfolio/title-criteria-templates.vue'),
        meta: {
          title: '职称资格条件模板',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'profile',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/ethics-sanction',
        name: 'PortfolioEthicsSanctionAdmin',
        component: () => import('@/views/portfolio/ethics-sanction-admin.vue'),
        meta: {
          title: '师德处分',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'safety',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/compliance-threshold',
        name: 'PortfolioComplianceThresholdAdmin',
        component: () => import('@/views/portfolio/compliance-threshold-admin.vue'),
        meta: {
          title: '结构合规阈值',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'control',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/reporting',
        name: 'PortfolioReportingAdmin',
        component: () => import('@/views/portfolio/reporting-admin.vue'),
        meta: {
          title: '上级报送共享',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'cloud-upload',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'school/expert-assignment',
        name: 'PortfolioExpertAssignmentAdmin',
        component: () => import('@/views/portfolio/expert-assignment-admin.vue'),
        meta: {
          title: '外部专家授权',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'user-add',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioGovernanceMenuMeta,
        },
      },
      {
        path: 'expert/workbench',
        name: 'PortfolioExpertWorkbench',
        component: () => import('@/views/portfolio/expert-workbench.vue'),
        meta: {
          title: '专家评审工作台',
          roles: ALL_ROLES,
          icon: 'audit',
          hideInMenu: false,
          keepAlive: true,
          portfolioWorkShells: EXTERNAL_EXPERT_WORK_SHELLS,
        },
      },
      {
        path: 'expert/review',
        name: 'PortfolioExpertReview',
        component: () => import('@/views/portfolio/expert-review.vue'),
        meta: {
          title: '外部专家脱敏审阅',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
          portfolioWorkShells: EXPERT_REVIEW_WORK_SHELLS,
        },
      },
      {
        path: 'expert/evaluation-fill',
        name: 'PortfolioExpertEvaluationFill',
        component: () => import('@/views/portfolio/evaluation-fill-admin.vue'),
        meta: {
          title: '外部专家评价填报',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
          portfolioWorkShells: EXPERT_REVIEW_WORK_SHELLS,
        },
      },
      {
        path: 'admin/correction',
        name: 'PortfolioCorrectionAdmin',
        component: () => import('@/views/portfolio/correction-admin.vue'),
        meta: {
          title: '纠错处理',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'exception',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'admin/source-fix',
        name: 'PortfolioSourceFixAdmin',
        component: () => import('@/views/portfolio/source-fix-admin.vue'),
        meta: {
          title: '源修复重算',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'sync',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'admin/indicator/platform',
        name: 'PortfolioIndicatorPlatform',
        component: () => import('@/views/portfolio/indicator-platform-admin.vue'),
        meta: {
          title: '平台指标资产',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'table',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator',
        name: 'PortfolioIndicatorTenant',
        component: () => import('@/views/portfolio/indicator-tenant-admin.vue'),
        meta: {
          title: '租户指标配置',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'setting',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator/eligibility',
        name: 'PortfolioIndicatorEligibility',
        component: () => import('@/views/portfolio/indicator-eligibility.vue'),
        meta: {
          title: '资格规则',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'branches',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator/publish-wizard',
        name: 'PortfolioIndicatorPublishWizard',
        component: () => import('@/views/portfolio/indicator-publish-wizard.vue'),
        meta: {
          title: '规则发布向导',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'rocket',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: false,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator/history',
        name: 'PortfolioIndicatorHistory',
        component: () => import('@/views/portfolio/indicator-history.vue'),
        meta: {
          title: '规则快照历史',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'history',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator/ops',
        name: 'PortfolioIndicatorOps',
        component: () => import('@/views/portfolio/indicator-ops-admin.vue'),
        meta: {
          title: '计分与审计',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'audit',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator-dashboard',
        name: 'PortfolioIndicatorDashboard',
        component: () => import('@/views/portfolio/indicator-dashboard-admin.vue'),
        meta: {
          title: '指标看板',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'bar-chart',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'admin/indicator/reference-status',
        name: 'PortfolioIndicatorReferenceStatus',
        component: () => import('@/views/portfolio/indicator-reference-status.vue'),
        meta: {
          title: '指标引用状态',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'link',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...indicatorMenuMeta,
        },
      },
      {
        path: 'teacher/indicator',
        name: 'PortfolioTeacherIndicator',
        component: () => import('@/views/portfolio/teacher-indicator.vue'),
        meta: {
          title: '资格评估',
          roles: ALL_ROLES,
          icon: 'safety-certificate',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
      {
        path: 'teacher/dual-teacher-apply',
        redirect: to => ({
          path: '/portfolio/scene/dual-teacher',
          query: { ...to.query },
        }),
        meta: {
          title: '双师认定申请（旧入口）',
          roles: ALL_ROLES,
          hideInMenu: true,
          keepAlive: false,
        },
      },
      {
        path: 'admin/dual-teacher',
        name: 'PortfolioDualTeacherAdmin',
        component: () => import('@/views/portfolio/dual-teacher-admin.vue'),
        meta: {
          title: '双师认定',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'audit',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioDualTeacherMenuMeta,
        },
      },
      {
        path: 'admin/dual-teacher/analytics',
        name: 'PortfolioDualTeacherAnalytics',
        component: () => import('@/views/portfolio/dual-teacher-analytics.vue'),
        meta: {
          title: '双师分析',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'pie-chart',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDualTeacherMenuMeta,
        },
      },
      {
        path: 'admin/external-teacher',
        name: 'PortfolioExternalTeacherAdmin',
        component: () => import('@/views/portfolio/external-teacher-admin.vue'),
        meta: {
          title: '外聘教师',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'team',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/policy-ledger',
        name: 'PortfolioPolicyLedgerAdmin',
        component: () => import('@/views/portfolio/policy-ledger-admin.vue'),
        meta: {
          title: '政策专项台账',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'book',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/development-plan',
        name: 'PortfolioDevelopmentPlanAdmin',
        component: () => import('@/views/portfolio/development-plan-admin.vue'),
        meta: {
          title: '教师年度规划',
          roles: ALL_ROLES,
          icon: 'calendar',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'department/development-plan',
        name: 'PortfolioDevelopmentPlanDepartmentAdmin',
        component: () => import('@/views/portfolio/development-plan-department-admin.vue'),
        meta: {
          title: '部门年度规划',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'cluster',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/development-plan-review',
        name: 'PortfolioDevelopmentPlanReview',
        component: () => import('@/views/portfolio/development-plan-review.vue'),
        meta: {
          title: '规划审核',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'audit',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'admin/teacher-report',
        name: 'PortfolioTeacherReportAdmin',
        component: () => import('@/views/portfolio/teacher-report-admin.vue'),
        meta: {
          title: '文本分析报告',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'file-text',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/honor-library',
        name: 'PortfolioHonorLibraryAdmin',
        component: () => import('@/views/portfolio/honor-library-admin.vue'),
        meta: {
          title: '荣誉库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'trophy',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/key-teacher',
        name: 'PortfolioKeyTeacherAdmin',
        component: () => import('@/views/portfolio/key-teacher-admin.vue'),
        meta: {
          title: '骨干/带头人',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'crown',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/double-duty',
        name: 'PortfolioDoubleDutyAdmin',
        component: () => import('@/views/portfolio/double-duty-admin.vue'),
        meta: {
          title: '双肩挑台账',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'swap',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/teacher-salary',
        name: 'PortfolioTeacherSalaryAdmin',
        component: () => import('@/views/portfolio/teacher-salary-admin.vue'),
        meta: {
          title: '教师工资',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'pay-circle',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/teacher-library',
        name: 'PortfolioTeacherLibraryAdmin',
        component: () => import('@/views/portfolio/teacher-library-admin.vue'),
        meta: {
          title: '图书借阅',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'read',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/teacher-recommendation',
        name: 'PortfolioTeacherRecommendationAdmin',
        component: () => import('@/views/portfolio/teacher-recommendation-admin.vue'),
        meta: {
          title: '优秀教师推荐',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'like',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/development-record',
        name: 'PortfolioDevelopmentRecordAdmin',
        component: () => import('@/views/portfolio/development-record-admin.vue'),
        meta: {
          title: '发展档案库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'database',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/achievement-comprehensive',
        name: 'PortfolioAchievementComprehensive',
        component: () => import('@/views/portfolio/achievement-comprehensive.vue'),
        meta: {
          title: '成果综合查询',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'search',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/portrait-template',
        name: 'PortfolioPortraitTemplateAdmin',
        component: () => import('@/views/portfolio/portrait-template-admin.vue'),
        meta: {
          title: '画像设置',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'layout',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/evaluation-task',
        name: 'PortfolioEvaluationTaskAdmin',
        component: () => import('@/views/portfolio/evaluation-task-admin.vue'),
        meta: {
          title: '多元评价',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'form',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioEvaluationMenuMeta,
        },
      },
      {
        path: 'admin/evaluation-fill',
        name: 'PortfolioEvaluationFillAdmin',
        component: () => import('@/views/portfolio/evaluation-fill-admin.vue'),
        meta: {
          title: '评价填报',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'edit',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioEvaluationMenuMeta,
        },
      },
      {
        path: 'admin/evaluation-comprehensive',
        name: 'PortfolioEvaluationComprehensiveAdmin',
        component: () => import('@/views/portfolio/evaluation-comprehensive-admin.vue'),
        meta: {
          title: '评价综合分析',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'bar-chart',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioEvaluationMenuMeta,
        },
      },
      {
        path: 'admin/training-archive',
        name: 'PortfolioTrainingArchiveAdmin',
        component: () => import('@/views/portfolio/training-archive-admin.vue'),
        meta: {
          title: '培训档案',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'read',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'department/dept-one-table',
        name: 'PortfolioDeptOneTable',
        component: () => import('@/views/portfolio/dept-one-table.vue'),
        meta: {
          title: '部门一张表',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'table',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'admin/teacher-analytics',
        name: 'PortfolioTeacherAnalyticsDashboard',
        component: () => import('@/views/portfolio/teacher-analytics-dashboard.vue'),
        meta: {
          title: '师资分析看板',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'dashboard',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioAnalyticsMenuMeta,
        },
      },
      {
        path: 'admin/alert-center',
        name: 'PortfolioAlertCenter',
        component: () => import('@/views/portfolio/alert-center.vue'),
        meta: {
          title: '预警中心',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'alert',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioAnalyticsMenuMeta,
        },
      },
      {
        path: 'admin/teacher-pk',
        name: 'PortfolioTeacherPkAnalytics',
        component: () => import('@/views/portfolio/teacher-pk-analytics.vue'),
        meta: {
          title: '教师 PK',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'swap',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioAnalyticsMenuMeta,
        },
      },
      {
        path: 'admin/annual-report-analytics',
        name: 'PortfolioAnnualReportAnalytics',
        component: () => import('@/views/portfolio/annual-report-analytics.vue'),
        meta: {
          title: '年度报告',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'file-text',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioAnalyticsMenuMeta,
        },
      },
      {
        path: 'department/report',
        name: 'PortfolioDepartmentReport',
        component: () => import('@/views/portfolio/department-report.vue'),
        meta: {
          title: '院系报告',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'file-text',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'department/cockpit',
        name: 'PortfolioDepartmentCockpit',
        component: () => import('@/views/portfolio/department-cockpit.vue'),
        meta: {
          title: '院系驾驶舱',
          roles: ALL_ROLES,
          requirePortfolioReviewer: true,
          icon: 'dashboard',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioDepartmentMenuMeta,
        },
      },
      {
        path: 'school/cockpit',
        name: 'PortfolioSchoolCockpit',
        component: () => import('@/views/portfolio/school-cockpit.vue'),
        meta: {
          title: '学校驾驶舱',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'dashboard',
          hideInMenu: false,
          keepAlive: true,
          ...portfolioAnalyticsMenuMeta,
        },
      },
      {
        path: 'admin/evaluation-workgroup',
        name: 'PortfolioEvaluationWorkgroupNav',
        component: () => import('@/views/portfolio/evaluation-workgroup-admin.vue'),
        meta: {
          title: '评价工作组',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'team',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          portfolioDomain: true,
          ...portfolioOrgMenuMeta,
        },
      },
      {
        path: 'admin/teaching-resource-library',
        name: 'PortfolioTeachingResourceLibrary',
        component: () => import('@/views/portfolio/teaching-resource-library-admin.vue'),
        meta: {
          title: '教学资源库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'read',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/research-resource-library',
        name: 'PortfolioResearchResourceLibrary',
        component: () => import('@/views/portfolio/research-resource-library-admin.vue'),
        meta: {
          title: '科研资源库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'experiment',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/practice-resource-library',
        name: 'PortfolioPracticeResourceLibrary',
        component: () => import('@/views/portfolio/practice-resource-library-admin.vue'),
        meta: {
          title: '实践资源库',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'tool',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'admin/national-achievement',
        name: 'PortfolioNationalAchievement',
        component: () => import('@/views/portfolio/national-achievement-admin.vue'),
        meta: {
          title: '国家级成果',
          ...PORTFOLIO_ADMIN_ROUTE_META,
          icon: 'crown',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioResourceMenuMeta,
        },
      },
      {
        path: 'teacher/one-table',
        name: 'PortfolioTeacherOneTable',
        component: () => import('@/views/portfolio/teacher-one-table.vue'),
        meta: {
          title: '教师一张表',
          roles: ALL_ROLES,
          icon: 'table',
          hideInMenu: false,
          ...MENU_SECONDARY,
          keepAlive: true,
          ...portfolioTeacherMenuMeta,
        },
      },
    ],
  },
]
