/**
 * 教师（SCH_TECH / CROP_ADMIN / CROP_USER）路由
 *
 * 阅卷端教师工作台按真实使用流程组织：
 *   ① 考试准备       menuGroupOrder=1：准备工作台 → 考试列表 → 题目 / 名册 → 形态模板 / 母版 / 印刷包
 *   ② 扫描与识别     menuGroupOrder=2：扫描上传 → 实时看板 → 异常处理 → 影像 / 设备 / OCR
 *   ③ 教师复核       menuGroupOrder=3：OCR / AI 建议后的教师确认链
 *   ④ 阅卷组织正评   menuGroupOrder=4：阅卷组织 → 分派方案 → 任务池 → 仲裁 / 抽检 / 经验
 *   ⑤ 成绩与申诉     menuGroupOrder=5：缺考确认 → 成绩确认 / 发布 → 申诉处理
 *   ⑥ 归档与分析     menuGroupOrder=6：统计分析 → 导出任务 → 电子 / 纸质归档
 */
import type { RouteRecordRaw } from 'vue-router'
import { RoleEnum } from '@/utils/permission'

const TEACHER_ROLES = [RoleEnum.SCH_TECH, RoleEnum.CROP_ADMIN, RoleEnum.CROP_USER]
const ALL_TEACHER_ROLES = [RoleEnum.SUPER_ADMIN, ...TEACHER_ROLES]

export const teacherRoutes: RouteRecordRaw[] = [
  {
    path: '/teacher',
    name: 'TeacherLayout',
    component: () => import('@/layout/index.vue'),
    redirect: '/teacher/exam-list',
    meta: {
      title: '阅卷工作台',
      roles: ALL_TEACHER_ROLES,
      icon: 'audit',
      hideInMenu: false,
    },
    children: [
      {
        path: 'marking-overview',
        redirect: { name: 'TeacherExamList' },
      },

      // ─── ① 考试准备 ──────────────────────────────────────
      {
        path: 'exam-prep-workbench',
        name: 'TeacherExamPrepWorkbench',
        component: () => import('@/views/teacher/exam-prep-workbench.vue'),
        meta: {
          title: '考试准备',
          roles: TEACHER_ROLES,
          icon: 'schedule',
          hideInMenu: false,
          keepAlive: false,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'exam-list',
        name: 'TeacherExamList',
        component: () => import('@/views/teacher/exam-list.vue'),
        meta: {
          title: '考试工作台',
          roles: TEACHER_ROLES,
          icon: 'dashboard',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'paper-template',
        name: 'TeacherPaperTemplate',
        component: () => import('@/views/teacher/paper-template.vue'),
        meta: {
          title: '试卷题目',
          roles: TEACHER_ROLES,
          icon: 'file-text',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'answer-sheet-template',
        name: 'TeacherAnswerSheetTemplate',
        component: () => import('@/views/teacher/answer-sheet-template.vue'),
        meta: {
          title: '答卷页模板',
          roles: TEACHER_ROLES,
          icon: 'form',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'candidate-roster',
        name: 'TeacherCandidateRoster',
        component: () => import('@/views/teacher/candidate-roster.vue'),
        meta: {
          title: '考生名册',
          roles: TEACHER_ROLES,
          icon: 'team',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'exam/:examId/detail',
        name: 'TeacherExamDetail',
        component: () => import('@/views/teacher/exam-detail.vue'),
        meta: {
          title: '考试详情',
          roles: TEACHER_ROLES,
          icon: 'eye',
          hideInMenu: true,
          noCache: true,
          activeMenu: '/teacher/exam-list',
        },
      },

      {
        path: 'paper-master',
        name: 'TeacherPaperMaster',
        component: () => import('@/views/teacher/paper-master.vue'),
        meta: {
          title: '试卷母版',
          roles: TEACHER_ROLES,
          icon: 'file-pdf',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },
      {
        path: 'print-package',
        name: 'TeacherPrintPackage',
        component: () => import('@/views/teacher/print-package.vue'),
        meta: {
          title: '印刷包管理',
          roles: TEACHER_ROLES,
          icon: 'container',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'exam-prep',
          menuGroupTitle: '考试准备',
          menuGroupIcon: 'schedule',
          menuGroupOrder: 1,
        },
      },

      // ─── ② 扫描与识别 ────────────────────────────────────
      {
        path: 'scan-upload',
        name: 'TeacherScanUpload',
        component: () => import('@/views/teacher/scan-upload.vue'),
        meta: {
          title: '扫描录入',
          roles: TEACHER_ROLES,
          icon: 'cloud-upload',
          hideInMenu: false,
          menuGroup: 'scan',
          menuGroupTitle: '扫描与识别',
          menuGroupIcon: 'scan',
          menuGroupOrder: 2,
        },
      },
      {
        path: 'scan-live-monitor',
        name: 'TeacherScanLiveMonitor',
        component: () => import('@/views/teacher/scan-live-monitor.vue'),
        meta: {
          title: '扫描监控中控台',
          roles: TEACHER_ROLES,
          icon: 'thunderbolt',
          hideInMenu: false,
          // 实时 SSE 看板进入即建立连接、退出即释放，不应保留状态
          keepAlive: false,
          noCache: true,
          menuGroup: 'scan',
          menuGroupTitle: '扫描与识别',
          menuGroupIcon: 'scan',
          menuGroupOrder: 2,
        },
      },
      {
        path: 'image-ledger',
        name: 'TeacherImageLedger',
        component: () => import('@/views/teacher/image-ledger.vue'),
        meta: {
          title: '影像账本',
          roles: TEACHER_ROLES,
          icon: 'book',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'scan',
          menuGroupTitle: '扫描与识别',
          menuGroupIcon: 'scan',
          menuGroupOrder: 2,
        },
      },
      {
        path: 'printer-management',
        name: 'TeacherPrinterManagement',
        component: () => import('@/views/teacher/printer-management.vue'),
        meta: {
          title: '设备管理',
          roles: TEACHER_ROLES,
          icon: 'printer',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'scan',
          menuGroupTitle: '扫描与识别',
          menuGroupIcon: 'scan',
          menuGroupOrder: 2,
        },
      },
      {
        path: 'ocr-settings',
        name: 'TeacherOcrSettings',
        component: () => import('@/views/teacher/ocr-settings.vue'),
        meta: {
          title: 'OCR 状态',
          roles: TEACHER_ROLES,
          icon: 'file-search',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'scan',
          menuGroupTitle: '扫描与识别',
          menuGroupIcon: 'scan',
          menuGroupOrder: 2,
        },
      },

      // ─── ③ 教师复核 ──────────────────────────────────────
      {
        path: 'review-workspace',
        name: 'TeacherReviewWorkspace',
        component: () => import('@/views/teacher/review-workspace.vue'),
        meta: {
          title: 'OCR/AI 复核',
          roles: TEACHER_ROLES,
          icon: 'edit',
          hideInMenu: true,
          layoutWide: true,
          menuGroup: 'teacher-review',
          menuGroupTitle: '教师复核',
          menuGroupIcon: 'audit',
          menuGroupOrder: 3,
        },
      },
      {
        path: 'review-progress',
        name: 'TeacherReviewProgress',
        component: () => import('@/views/teacher/review-progress.vue'),
        meta: {
          title: '进度看板',
          roles: TEACHER_ROLES,
          icon: 'line-chart',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'teacher-review',
          menuGroupTitle: '教师复核',
          menuGroupIcon: 'audit',
          menuGroupOrder: 3,
        },
      },
      {
        path: 'review-batch-confirm',
        name: 'TeacherReviewBatchConfirm',
        component: () => import('@/views/teacher/review-batch-confirm.vue'),
        meta: {
          title: '批量审核',
          roles: TEACHER_ROLES,
          icon: 'check-circle',
          hideInMenu: false,
          menuGroup: 'teacher-review',
          menuGroupTitle: '教师复核',
          menuGroupIcon: 'audit',
          menuGroupOrder: 3,
        },
      },

      // ─── ④ 阅卷组织正评 ──────────────────────────────────
      {
        path: 'review-assignment',
        name: 'TeacherReviewAssignment',
        component: () => import('@/views/teacher/review-assignment.vue'),
        meta: {
          title: '分派方案',
          roles: TEACHER_ROLES,
          icon: 'deployment-unit',
          hideInMenu: true,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
          activeMenu: '/teacher/marking-organization',
        },
      },
      {
        path: 'marking-organization',
        name: 'TeacherMarkingOrganizationIndex',
        component: () => import('@/views/admin/marking-organization/index.vue'),
        meta: {
          title: '阅卷安排',
          roles: TEACHER_ROLES,
          icon: 'team',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
        },
      },
      {
        path: 'review-arbitration',
        name: 'TeacherReviewArbitration',
        component: () => import('@/views/teacher/review-arbitration.vue'),
        meta: {
          title: '仲裁裁定',
          roles: TEACHER_ROLES,
          icon: 'solution',
          hideInMenu: false,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
        },
      },
      {
        path: 'review/task/:taskId',
        name: 'TeacherReviewTaskDetail',
        component: () => import('@/views/teacher/review-task-detail.vue'),
        meta: {
          title: '批阅任务',
          roles: TEACHER_ROLES,
          icon: 'edit',
          hideInMenu: true,
          noCache: true,
          layoutWide: true,
          activeMenu: '/teacher/review-progress',
        },
      },

      // ─── ④ 阅卷组织正评（MarkingOrganization 主链） ─────────
      {
        path: 'marking-task-pool',
        name: 'TeacherMarkingTaskPool',
        component: () => import('@/views/teacher/marking-task-pool.vue'),
        meta: {
          title: '阅卷任务池',
          roles: TEACHER_ROLES,
          icon: 'cluster',
          hideInMenu: false,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
        },
      },
      {
        path: 'marking-spot-check',
        name: 'TeacherMarkingSpotCheck',
        component: () => import('@/views/teacher/marking-spot-check.vue'),
        meta: {
          title: '抽检处理',
          roles: TEACHER_ROLES,
          icon: 'aim',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
        },
      },
      {
        path: 'grading-experience',
        name: 'TeacherGradingExperience',
        component: () => import('@/views/teacher/grading-experience-hub.vue'),
        meta: {
          title: '批改经验库',
          roles: TEACHER_ROLES,
          icon: 'bulb',
          hideInMenu: true,
          keepAlive: true,
          menuGroup: 'formal-marking',
          menuGroupTitle: '阅卷组织正评',
          menuGroupIcon: 'highlight',
          menuGroupOrder: 4,
        },
      },
      {
        path: 'marking-task/:taskId',
        name: 'TeacherMarkingTaskDetail',
        component: () => import('@/views/teacher/marking-task-detail.vue'),
        meta: {
          title: '阅卷工作台',
          roles: TEACHER_ROLES,
          icon: 'highlight',
          hideInMenu: true,
          noCache: true,
          layoutWide: true,
          activeMenu: '/teacher/marking-task-pool',
        },
      },

      // ─── ⑤ 成绩与申诉 ────────────────────────────────────
      {
        path: 'absence-confirm',
        name: 'TeacherAbsenceConfirm',
        component: () => import('@/views/teacher/absence-confirm.vue'),
        meta: {
          title: '缺考确认',
          roles: TEACHER_ROLES,
          icon: 'user-delete',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'score-appeal',
          menuGroupTitle: '成绩与申诉',
          menuGroupIcon: 'trophy',
          menuGroupOrder: 5,
        },
      },
      {
        path: 'score-finalize',
        name: 'TeacherScoreFinalize',
        component: () => import('@/views/teacher/score-finalize.vue'),
        meta: {
          title: '成绩确认与发布',
          roles: TEACHER_ROLES,
          icon: 'check-square',
          hideInMenu: false,
          menuGroup: 'score-appeal',
          menuGroupTitle: '成绩与申诉',
          menuGroupIcon: 'trophy',
          menuGroupOrder: 5,
        },
      },
      {
        path: 'score-publish',
        redirect: { name: 'TeacherScoreFinalize' },
        meta: {
          title: '成绩发布',
          roles: TEACHER_ROLES,
          icon: 'notification',
          hideInMenu: true,
          menuGroup: 'score-appeal',
          menuGroupTitle: '成绩与申诉',
          menuGroupIcon: 'trophy',
          menuGroupOrder: 5,
          activeMenu: '/teacher/score-finalize',
        },
      },
      {
        path: 'appeal-handle',
        name: 'TeacherAppealHandle',
        component: () => import('@/views/teacher/appeal-handle.vue'),
        meta: {
          title: '复核处理',
          roles: TEACHER_ROLES,
          icon: 'interaction',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'score-appeal',
          menuGroupTitle: '成绩与申诉',
          menuGroupIcon: 'trophy',
          menuGroupOrder: 5,
        },
      },

      // ─── ⑥ 归档与分析 ────────────────────────────────────
      {
        path: 'statistics',
        name: 'TeacherStatistics',
        component: () => import('@/views/teacher/statistics.vue'),
        meta: {
          title: '成绩统计',
          roles: TEACHER_ROLES,
          icon: 'bar-chart',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'archive-analysis',
          menuGroupTitle: '归档与分析',
          menuGroupIcon: 'safety-certificate',
          menuGroupOrder: 6,
        },
      },
      {
        path: 'exam-exports',
        name: 'TeacherExamExports',
        component: () => import('@/views/common/exam-export-tasks.vue'),
        meta: {
          title: '导出任务',
          roles: TEACHER_ROLES,
          icon: 'cloud-download',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'archive-analysis',
          menuGroupTitle: '归档与分析',
          menuGroupIcon: 'safety-certificate',
          menuGroupOrder: 6,
        },
      },

      // ─── ⑥ 归档与分析 ────────────────────────────────────
      {
        path: 'archive-list',
        name: 'TeacherArchiveList',
        component: () => import('@/views/teacher/archive/archive-list.vue'),
        meta: {
          title: '归档列表',
          roles: TEACHER_ROLES,
          icon: 'inbox',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'archive-analysis',
          menuGroupTitle: '归档与分析',
          menuGroupIcon: 'safety-certificate',
          menuGroupOrder: 6,
        },
      },
      {
        path: 'archive/:archiveId/detail',
        name: 'TeacherArchiveDetail',
        component: () => import('@/views/teacher/archive/archive-detail.vue'),
        meta: {
          title: '归档详情',
          roles: TEACHER_ROLES,
          icon: 'eye',
          hideInMenu: true,
          noCache: true,
          activeMenu: '/teacher/archive-list',
        },
      },
      // 历史纸质试卷扫描入库 / tag / 检索 / OCR / 归档；独立于批改主链与考后归档主链
      {
        path: 'paper-archive-list',
        name: 'TeacherPaperArchiveList',
        component: () => import('@/views/teacher/paper-archive/paper-archive-list.vue'),
        meta: {
          title: '历史纸质档案',
          roles: TEACHER_ROLES,
          icon: 'folder-open',
          hideInMenu: false,
          keepAlive: true,
          menuGroup: 'archive-analysis',
          menuGroupTitle: '归档与分析',
          menuGroupIcon: 'safety-certificate',
          menuGroupOrder: 6,
        },
      },
      {
        path: 'marking-organization/:organizationId',
        name: 'TeacherMarkingOrganizationDetail',
        component: () => import('@/views/admin/marking-organization/detail.vue'),
        meta: {
          title: '组织详情',
          roles: TEACHER_ROLES,
          icon: 'setting',
          hideInMenu: true,
          noCache: true,
          activeMenu: '/teacher/marking-organization',
        },
      },
      {
        path: 'marking-organization/:organizationId/sessions',
        name: 'TeacherMarkingOrganizationSessions',
        component: () => import('@/views/admin/marking-organization/sessions.vue'),
        meta: {
          title: '试评 / 正评',
          roles: TEACHER_ROLES,
          icon: 'play-circle',
          hideInMenu: true,
          noCache: true,
          activeMenu: '/teacher/marking-organization',
        },
      },
      {
        path: 'paper-archive/:archiveSetId/detail',
        name: 'TeacherPaperArchiveDetail',
        component: () => import('@/views/teacher/paper-archive/paper-archive-detail.vue'),
        meta: {
          title: '纸质档案详情',
          roles: TEACHER_ROLES,
          icon: 'eye',
          hideInMenu: true,
          noCache: true,
          activeMenu: '/teacher/paper-archive-list',
        },
      },
    ],
  },
]
