/** 认证类型 - AccreditationTypeEnum */
export enum AccreditationTypeCode {
  ENGINEERING_ACCREDITATION = 'ENGINEERING_ACCREDITATION',
  TEACHER_ACCREDITATION = 'TEACHER_ACCREDITATION',
  MEDICAL_HEALTH_ACCREDITATION = 'MEDICAL_HEALTH_ACCREDITATION',
  ART_DESIGN_QUALITY_EVALUATION = 'ART_DESIGN_QUALITY_EVALUATION',
  ECONOMICS_FINANCE_QUALITY_EVALUATION = 'ECONOMICS_FINANCE_QUALITY_EVALUATION',
  LAW_QUALITY_EVALUATION = 'LAW_QUALITY_EVALUATION',
  AGRICULTURE_ACCREDITATION = 'AGRICULTURE_ACCREDITATION',
  GENERAL_QUALITY_EVALUATION = 'GENERAL_QUALITY_EVALUATION',
}

export const ALL_ACCREDITATION_TYPE_CODES: readonly AccreditationTypeCode[] = [
  AccreditationTypeCode.ENGINEERING_ACCREDITATION,
  AccreditationTypeCode.TEACHER_ACCREDITATION,
  AccreditationTypeCode.MEDICAL_HEALTH_ACCREDITATION,
  AccreditationTypeCode.ART_DESIGN_QUALITY_EVALUATION,
  AccreditationTypeCode.ECONOMICS_FINANCE_QUALITY_EVALUATION,
  AccreditationTypeCode.LAW_QUALITY_EVALUATION,
  AccreditationTypeCode.AGRICULTURE_ACCREDITATION,
  AccreditationTypeCode.GENERAL_QUALITY_EVALUATION,
]

export const AccreditationTypeDescription: Record<AccreditationTypeCode, string> = {
  [AccreditationTypeCode.ENGINEERING_ACCREDITATION]: '工程教育专业认证',
  [AccreditationTypeCode.TEACHER_ACCREDITATION]: '师范类专业认证',
  [AccreditationTypeCode.MEDICAL_HEALTH_ACCREDITATION]: '医学健康类专业认证',
  [AccreditationTypeCode.ART_DESIGN_QUALITY_EVALUATION]: '艺术与设计类专业质量评价',
  [AccreditationTypeCode.ECONOMICS_FINANCE_QUALITY_EVALUATION]: '财经类专业质量评价',
  [AccreditationTypeCode.LAW_QUALITY_EVALUATION]: '法学类专业质量评价',
  [AccreditationTypeCode.AGRICULTURE_ACCREDITATION]: '农学类专业认证或质量评价',
  [AccreditationTypeCode.GENERAL_QUALITY_EVALUATION]: '普通高等学校教学质量评价',
}
