/** 归档材料类型 */
export enum ArchiveMaterialTypeCode {
  VOLUME_COVER = 'VOLUME_COVER',
  VOLUME_CATALOG = 'VOLUME_CATALOG',
  TEACHING_SYLLABUS = 'TEACHING_SYLLABUS',
  ASSESSMENT_SYLLABUS = 'ASSESSMENT_SYLLABUS',
  TEACHING_SCHEDULE = 'TEACHING_SCHEDULE',
  EXAM_PROPOSAL_REVIEW = 'EXAM_PROPOSAL_REVIEW',
  EXAM_PAPER_APPROVAL = 'EXAM_PAPER_APPROVAL',
  EXAM_SPECIFICATION = 'EXAM_SPECIFICATION',
  QUESTION_BANK_PLAN = 'QUESTION_BANK_PLAN',
  BLANK_EXAM_PAPER_A = 'BLANK_EXAM_PAPER_A',
  BLANK_EXAM_PAPER_B = 'BLANK_EXAM_PAPER_B',
  RESERVE_EXAM_PAPER = 'RESERVE_EXAM_PAPER',
  MAKEUP_EXAM_PAPER = 'MAKEUP_EXAM_PAPER',
  ANSWER_RUBRIC_A = 'ANSWER_RUBRIC_A',
  ANSWER_RUBRIC_B = 'ANSWER_RUBRIC_B',
  ANSWER_RUBRIC_RESERVE = 'ANSWER_RUBRIC_RESERVE',
  ANSWER_RUBRIC_MAKEUP = 'ANSWER_RUBRIC_MAKEUP',
  COURSE_GRADING_BASIS = 'COURSE_GRADING_BASIS',
  GRADING_INSTRUCTION = 'GRADING_INSTRUCTION',
  EXAM_FORM_CHANGE = 'EXAM_FORM_CHANGE',
  STUDENT_LEARNING_RECORD = 'STUDENT_LEARNING_RECORD',
  EXAM_VENUE_RECORD = 'EXAM_VENUE_RECORD',
  INVIGILATION_RECORD = 'INVIGILATION_RECORD',
  ATTENDANCE_SHEET = 'ATTENDANCE_SHEET',
  PATROL_RECORD = 'PATROL_RECORD',
  TRANSCRIPT = 'TRANSCRIPT',
  ITEMIZED_SCORE = 'ITEMIZED_SCORE',
  EXAM_ANALYSIS = 'EXAM_ANALYSIS',
  COURSE_OBJECTIVE_REPORT = 'COURSE_OBJECTIVE_REPORT',
  TRAINING_OBJECTIVE_REPORT = 'TRAINING_OBJECTIVE_REPORT',
  PROCESS_ASSESSMENT = 'PROCESS_ASSESSMENT',
  STUDENT_EXAM_PAPER = 'STUDENT_EXAM_PAPER',
  ANSWER_SHEET = 'ANSWER_SHEET',
  OPTICAL_DISC = 'OPTICAL_DISC',
  PAPERLESS_EXAM_RESULT = 'PAPERLESS_EXAM_RESULT',
  AUDIO_VIDEO = 'AUDIO_VIDEO',
  THESIS = 'THESIS',
  WORK = 'WORK',
  LAB_PRACTICE = 'LAB_PRACTICE',
  SELF_CHECK_FORM = 'SELF_CHECK_FORM',
  TEACHING_SUMMARY = 'TEACHING_SUMMARY',
  RESEARCH_PROPOSAL = 'RESEARCH_PROPOSAL',
  RESEARCH_CONTRACT = 'RESEARCH_CONTRACT',
  RESEARCH_MIDTERM_REPORT = 'RESEARCH_MIDTERM_REPORT',
  RESEARCH_FINAL_REPORT = 'RESEARCH_FINAL_REPORT',
  RESEARCH_OUTCOME_SUMMARY = 'RESEARCH_OUTCOME_SUMMARY',
  THESIS_TASK_BOOK = 'THESIS_TASK_BOOK',
  THESIS_PROPOSAL = 'THESIS_PROPOSAL',
  THESIS_MIDTERM = 'THESIS_MIDTERM',
  THESIS_DEFENSE_RECORD = 'THESIS_DEFENSE_RECORD',
  STUDENT_STATUS_CARD = 'STUDENT_STATUS_CARD',
  GRADUATION_MATERIAL_LIST = 'GRADUATION_MATERIAL_LIST',
}

export const ALL_ARCHIVE_MATERIAL_TYPE_CODES: readonly ArchiveMaterialTypeCode[] = [
  ArchiveMaterialTypeCode.VOLUME_COVER,
  ArchiveMaterialTypeCode.VOLUME_CATALOG,
  ArchiveMaterialTypeCode.TEACHING_SYLLABUS,
  ArchiveMaterialTypeCode.ASSESSMENT_SYLLABUS,
  ArchiveMaterialTypeCode.TEACHING_SCHEDULE,
  ArchiveMaterialTypeCode.EXAM_PROPOSAL_REVIEW,
  ArchiveMaterialTypeCode.EXAM_PAPER_APPROVAL,
  ArchiveMaterialTypeCode.EXAM_SPECIFICATION,
  ArchiveMaterialTypeCode.QUESTION_BANK_PLAN,
  ArchiveMaterialTypeCode.BLANK_EXAM_PAPER_A,
  ArchiveMaterialTypeCode.BLANK_EXAM_PAPER_B,
  ArchiveMaterialTypeCode.RESERVE_EXAM_PAPER,
  ArchiveMaterialTypeCode.MAKEUP_EXAM_PAPER,
  ArchiveMaterialTypeCode.ANSWER_RUBRIC_A,
  ArchiveMaterialTypeCode.ANSWER_RUBRIC_B,
  ArchiveMaterialTypeCode.ANSWER_RUBRIC_RESERVE,
  ArchiveMaterialTypeCode.ANSWER_RUBRIC_MAKEUP,
  ArchiveMaterialTypeCode.COURSE_GRADING_BASIS,
  ArchiveMaterialTypeCode.GRADING_INSTRUCTION,
  ArchiveMaterialTypeCode.EXAM_FORM_CHANGE,
  ArchiveMaterialTypeCode.STUDENT_LEARNING_RECORD,
  ArchiveMaterialTypeCode.EXAM_VENUE_RECORD,
  ArchiveMaterialTypeCode.INVIGILATION_RECORD,
  ArchiveMaterialTypeCode.ATTENDANCE_SHEET,
  ArchiveMaterialTypeCode.PATROL_RECORD,
  ArchiveMaterialTypeCode.TRANSCRIPT,
  ArchiveMaterialTypeCode.ITEMIZED_SCORE,
  ArchiveMaterialTypeCode.EXAM_ANALYSIS,
  ArchiveMaterialTypeCode.COURSE_OBJECTIVE_REPORT,
  ArchiveMaterialTypeCode.TRAINING_OBJECTIVE_REPORT,
  ArchiveMaterialTypeCode.PROCESS_ASSESSMENT,
  ArchiveMaterialTypeCode.STUDENT_EXAM_PAPER,
  ArchiveMaterialTypeCode.ANSWER_SHEET,
  ArchiveMaterialTypeCode.OPTICAL_DISC,
  ArchiveMaterialTypeCode.PAPERLESS_EXAM_RESULT,
  ArchiveMaterialTypeCode.AUDIO_VIDEO,
  ArchiveMaterialTypeCode.THESIS,
  ArchiveMaterialTypeCode.WORK,
  ArchiveMaterialTypeCode.LAB_PRACTICE,
  ArchiveMaterialTypeCode.SELF_CHECK_FORM,
  ArchiveMaterialTypeCode.TEACHING_SUMMARY,
  ArchiveMaterialTypeCode.RESEARCH_PROPOSAL,
  ArchiveMaterialTypeCode.RESEARCH_CONTRACT,
  ArchiveMaterialTypeCode.RESEARCH_MIDTERM_REPORT,
  ArchiveMaterialTypeCode.RESEARCH_FINAL_REPORT,
  ArchiveMaterialTypeCode.RESEARCH_OUTCOME_SUMMARY,
  ArchiveMaterialTypeCode.THESIS_TASK_BOOK,
  ArchiveMaterialTypeCode.THESIS_PROPOSAL,
  ArchiveMaterialTypeCode.THESIS_MIDTERM,
  ArchiveMaterialTypeCode.THESIS_DEFENSE_RECORD,
  ArchiveMaterialTypeCode.STUDENT_STATUS_CARD,
  ArchiveMaterialTypeCode.GRADUATION_MATERIAL_LIST,
]
export const ArchiveMaterialTypeDescription: Record<ArchiveMaterialTypeCode, string> = {
  [ArchiveMaterialTypeCode.VOLUME_COVER]: '卷封面',
  [ArchiveMaterialTypeCode.VOLUME_CATALOG]: '卷内目录',
  [ArchiveMaterialTypeCode.TEACHING_SYLLABUS]: '教学大纲',
  [ArchiveMaterialTypeCode.ASSESSMENT_SYLLABUS]: '考核大纲',
  [ArchiveMaterialTypeCode.TEACHING_SCHEDULE]: '教学进度表',
  [ArchiveMaterialTypeCode.EXAM_PROPOSAL_REVIEW]: '命题审核表',
  [ArchiveMaterialTypeCode.EXAM_PAPER_APPROVAL]: '试卷审批表',
  [ArchiveMaterialTypeCode.EXAM_SPECIFICATION]: '命题双向细目表',
  [ArchiveMaterialTypeCode.QUESTION_BANK_PLAN]: '试题库建设及审核方案',
  [ArchiveMaterialTypeCode.BLANK_EXAM_PAPER_A]: '空白试卷A卷',
  [ArchiveMaterialTypeCode.BLANK_EXAM_PAPER_B]: '空白试卷B卷',
  [ArchiveMaterialTypeCode.RESERVE_EXAM_PAPER]: '备用试题',
  [ArchiveMaterialTypeCode.MAKEUP_EXAM_PAPER]: '补考试题',
  [ArchiveMaterialTypeCode.ANSWER_RUBRIC_A]: 'A卷答案评分标准',
  [ArchiveMaterialTypeCode.ANSWER_RUBRIC_B]: 'B卷答案评分标准',
  [ArchiveMaterialTypeCode.ANSWER_RUBRIC_RESERVE]: '备用试题答案评分标准',
  [ArchiveMaterialTypeCode.ANSWER_RUBRIC_MAKEUP]: '补考试题答案评分标准',
  [ArchiveMaterialTypeCode.COURSE_GRADING_BASIS]: '课程考核评分依据',
  [ArchiveMaterialTypeCode.GRADING_INSTRUCTION]: '阅卷说明',
  [ArchiveMaterialTypeCode.EXAM_FORM_CHANGE]: '考试形式变更申请表',
  [ArchiveMaterialTypeCode.STUDENT_LEARNING_RECORD]: '学生学习情况登记表',
  [ArchiveMaterialTypeCode.EXAM_VENUE_RECORD]: '考场记录',
  [ArchiveMaterialTypeCode.INVIGILATION_RECORD]: '监考记录',
  [ArchiveMaterialTypeCode.ATTENDANCE_SHEET]: '签到表',
  [ArchiveMaterialTypeCode.PATROL_RECORD]: '巡考记录',
  [ArchiveMaterialTypeCode.TRANSCRIPT]: '成绩单',
  [ArchiveMaterialTypeCode.ITEMIZED_SCORE]: '分项成绩',
  [ArchiveMaterialTypeCode.EXAM_ANALYSIS]: '试卷分析',
  [ArchiveMaterialTypeCode.COURSE_OBJECTIVE_REPORT]: '课程目标达成报告',
  [ArchiveMaterialTypeCode.TRAINING_OBJECTIVE_REPORT]: '培养目标达成评价报告',
  [ArchiveMaterialTypeCode.PROCESS_ASSESSMENT]: '过程性考核材料',
  [ArchiveMaterialTypeCode.STUDENT_EXAM_PAPER]: '学生试卷',
  [ArchiveMaterialTypeCode.ANSWER_SHEET]: '答题卡',
  [ArchiveMaterialTypeCode.OPTICAL_DISC]: '光盘',
  [ArchiveMaterialTypeCode.PAPERLESS_EXAM_RESULT]: '无纸化考试结果',
  [ArchiveMaterialTypeCode.AUDIO_VIDEO]: '音视频',
  [ArchiveMaterialTypeCode.THESIS]: '论文',
  [ArchiveMaterialTypeCode.WORK]: '作品',
  [ArchiveMaterialTypeCode.LAB_PRACTICE]: '实验实习材料',
  [ArchiveMaterialTypeCode.SELF_CHECK_FORM]: '试卷核查自查表',
  [ArchiveMaterialTypeCode.TEACHING_SUMMARY]: '教学一览表/课程教学总结',
  [ArchiveMaterialTypeCode.RESEARCH_PROPOSAL]: '立项申请书',
  [ArchiveMaterialTypeCode.RESEARCH_CONTRACT]: '项目合同书',
  [ArchiveMaterialTypeCode.RESEARCH_MIDTERM_REPORT]: '中期检查报告',
  [ArchiveMaterialTypeCode.RESEARCH_FINAL_REPORT]: '结项报告',
  [ArchiveMaterialTypeCode.RESEARCH_OUTCOME_SUMMARY]: '成果摘要',
  [ArchiveMaterialTypeCode.THESIS_TASK_BOOK]: '任务书',
  [ArchiveMaterialTypeCode.THESIS_PROPOSAL]: '开题报告',
  [ArchiveMaterialTypeCode.THESIS_MIDTERM]: '中期检查表',
  [ArchiveMaterialTypeCode.THESIS_DEFENSE_RECORD]: '答辩记录',
  [ArchiveMaterialTypeCode.STUDENT_STATUS_CARD]: '学籍卡',
  [ArchiveMaterialTypeCode.GRADUATION_MATERIAL_LIST]: '毕业材料清单',
}
