/** 归档包业务流事件类型 - ArchiveEventType */
export enum ArchiveEventTypeCode {
  CREATED = 'CREATED',
  PACKAGING_STARTED = 'PACKAGING_STARTED',
  PACKAGING_COMPLETED = 'PACKAGING_COMPLETED',
  PACKAGING_FAILED = 'PACKAGING_FAILED',
  STORED_DELIVERED = 'STORED_DELIVERED',
  APPRAISAL_REQUESTED = 'APPRAISAL_REQUESTED',
  APPRAISAL_DECIDED = 'APPRAISAL_DECIDED',
  RETENTION_EXTENDED = 'RETENTION_EXTENDED',
  DESTRUCTION_REQUESTED = 'DESTRUCTION_REQUESTED',
  DESTRUCTION_APPROVED = 'DESTRUCTION_APPROVED',
  DESTRUCTION_REJECTED = 'DESTRUCTION_REJECTED',
  DESTRUCTION_EXECUTING = 'DESTRUCTION_EXECUTING',
  DESTRUCTION_RETRY_FAILED = 'DESTRUCTION_RETRY_FAILED',
  DESTRUCTION_FAILED = 'DESTRUCTION_FAILED',
  DESTROYED = 'DESTROYED',
}

export const ALL_ARCHIVE_EVENT_TYPE_CODES: readonly ArchiveEventTypeCode[] = [
  ArchiveEventTypeCode.CREATED,
  ArchiveEventTypeCode.PACKAGING_STARTED,
  ArchiveEventTypeCode.PACKAGING_COMPLETED,
  ArchiveEventTypeCode.PACKAGING_FAILED,
  ArchiveEventTypeCode.STORED_DELIVERED,
  ArchiveEventTypeCode.APPRAISAL_REQUESTED,
  ArchiveEventTypeCode.APPRAISAL_DECIDED,
  ArchiveEventTypeCode.RETENTION_EXTENDED,
  ArchiveEventTypeCode.DESTRUCTION_REQUESTED,
  ArchiveEventTypeCode.DESTRUCTION_APPROVED,
  ArchiveEventTypeCode.DESTRUCTION_REJECTED,
  ArchiveEventTypeCode.DESTRUCTION_EXECUTING,
  ArchiveEventTypeCode.DESTRUCTION_RETRY_FAILED,
  ArchiveEventTypeCode.DESTRUCTION_FAILED,
  ArchiveEventTypeCode.DESTROYED,
]

export const ArchiveEventTypeDescription: Record<ArchiveEventTypeCode, string> = {
  [ArchiveEventTypeCode.CREATED]: '归档包创建',
  [ArchiveEventTypeCode.PACKAGING_STARTED]: '打包开始',
  [ArchiveEventTypeCode.PACKAGING_COMPLETED]: '打包完成',
  [ArchiveEventTypeCode.PACKAGING_FAILED]: '打包失败',
  [ArchiveEventTypeCode.STORED_DELIVERED]: '投递存储',
  [ArchiveEventTypeCode.APPRAISAL_REQUESTED]: '鉴定申请',
  [ArchiveEventTypeCode.APPRAISAL_DECIDED]: '鉴定决议',
  [ArchiveEventTypeCode.RETENTION_EXTENDED]: '保管期限延长',
  [ArchiveEventTypeCode.DESTRUCTION_REQUESTED]: '销毁申请',
  [ArchiveEventTypeCode.DESTRUCTION_APPROVED]: '销毁审批通过',
  [ArchiveEventTypeCode.DESTRUCTION_REJECTED]: '销毁审批拒绝',
  [ArchiveEventTypeCode.DESTRUCTION_EXECUTING]: '销毁执行已发起',
  [ArchiveEventTypeCode.DESTRUCTION_RETRY_FAILED]: '销毁执行单次失败',
  [ArchiveEventTypeCode.DESTRUCTION_FAILED]: '销毁执行终态失败',
  [ArchiveEventTypeCode.DESTROYED]: '销毁执行完成',
}
