/** 考试工作台优先推进原因 - ExamWorkbenchPriorityReasonCode */
export enum ExamWorkbenchPriorityReasonCode {
  SCAN_ATTENTION = 'SCAN_ATTENTION',
  UNBOUND_CANDIDATE_INCIDENT = 'UNBOUND_CANDIDATE_INCIDENT',
  MISSING_CANDIDATE_ROSTER = 'MISSING_CANDIDATE_ROSTER',
  OPEN_PROCESSING_TASK = 'OPEN_PROCESSING_TASK',
  PENDING_REVIEW_TASK = 'PENDING_REVIEW_TASK',
  UNCONFIRMED_GRADE = 'UNCONFIRMED_GRADE',
  CONFIRMED_UNPUBLISHED_SCORE = 'CONFIRMED_UNPUBLISHED_SCORE',
  PENDING_PUBLISH_REVIEW_OPEN = 'PENDING_PUBLISH_REVIEW_OPEN',
  PENDING_MY_PUBLISH_REVIEW = 'PENDING_MY_PUBLISH_REVIEW',
}

export const ALL_EXAM_WORKBENCH_PRIORITY_REASON_CODES: readonly ExamWorkbenchPriorityReasonCode[] = [
  ExamWorkbenchPriorityReasonCode.SCAN_ATTENTION,
  ExamWorkbenchPriorityReasonCode.UNBOUND_CANDIDATE_INCIDENT,
  ExamWorkbenchPriorityReasonCode.MISSING_CANDIDATE_ROSTER,
  ExamWorkbenchPriorityReasonCode.OPEN_PROCESSING_TASK,
  ExamWorkbenchPriorityReasonCode.PENDING_REVIEW_TASK,
  ExamWorkbenchPriorityReasonCode.PENDING_MY_PUBLISH_REVIEW,
  ExamWorkbenchPriorityReasonCode.PENDING_PUBLISH_REVIEW_OPEN,
  ExamWorkbenchPriorityReasonCode.UNCONFIRMED_GRADE,
  ExamWorkbenchPriorityReasonCode.CONFIRMED_UNPUBLISHED_SCORE,
]
