/**
 * 平台 Excel 导入 scene - ExcelImportSceneKey
 * code 等于枚举常量名，与后端唯一真源一致。
 */
export enum ExcelImportSceneKeyCode {
  QUALITY_WORKGROUP_MEMBER = 'QUALITY_WORKGROUP_MEMBER',
  QUALITY_PROCESS_RECORD = 'QUALITY_PROCESS_RECORD',
  QUALITY_INDIRECT_RESPONSE = 'QUALITY_INDIRECT_RESPONSE',
  QUALITY_SCORE_BATCH = 'QUALITY_SCORE_BATCH',
  PORTFOLIO_EXTERNAL_TEACHER = 'PORTFOLIO_EXTERNAL_TEACHER',
  PORTFOLIO_DUAL_TEACHER = 'PORTFOLIO_DUAL_TEACHER',
  PORTFOLIO_INDICATOR_DEFINITION = 'PORTFOLIO_INDICATOR_DEFINITION',
  PORTFOLIO_DEVELOPMENT_PLAN_HISTORY = 'PORTFOLIO_DEVELOPMENT_PLAN_HISTORY',
  PORTFOLIO_DEVELOPMENT_RECORD = 'PORTFOLIO_DEVELOPMENT_RECORD',
  PORTFOLIO_SCIENTIFIC_RESEARCH_FACT = 'PORTFOLIO_SCIENTIFIC_RESEARCH_FACT',
  MARK_ARCHIVE_EXTERNAL = 'MARK_ARCHIVE_EXTERNAL',
  MARK_PAPER_ARCHIVE_HISTORY = 'MARK_PAPER_ARCHIVE_HISTORY',
  MARK_ROSTER_EXCEL = 'MARK_ROSTER_EXCEL',
}

export const ALL_EXCEL_IMPORT_SCENE_KEY_CODES: readonly ExcelImportSceneKeyCode[] = [
  ExcelImportSceneKeyCode.QUALITY_WORKGROUP_MEMBER,
  ExcelImportSceneKeyCode.QUALITY_PROCESS_RECORD,
  ExcelImportSceneKeyCode.QUALITY_INDIRECT_RESPONSE,
  ExcelImportSceneKeyCode.QUALITY_SCORE_BATCH,
  ExcelImportSceneKeyCode.PORTFOLIO_EXTERNAL_TEACHER,
  ExcelImportSceneKeyCode.PORTFOLIO_DUAL_TEACHER,
  ExcelImportSceneKeyCode.PORTFOLIO_INDICATOR_DEFINITION,
  ExcelImportSceneKeyCode.PORTFOLIO_DEVELOPMENT_PLAN_HISTORY,
  ExcelImportSceneKeyCode.PORTFOLIO_DEVELOPMENT_RECORD,
  ExcelImportSceneKeyCode.PORTFOLIO_SCIENTIFIC_RESEARCH_FACT,
  ExcelImportSceneKeyCode.MARK_ARCHIVE_EXTERNAL,
  ExcelImportSceneKeyCode.MARK_PAPER_ARCHIVE_HISTORY,
  ExcelImportSceneKeyCode.MARK_ROSTER_EXCEL,
]
