/**
 * 通知类型枚举 - 与后端 NotificationTypeEnum 完全对应
 */
export enum NotificationTypeEnum {
  // --- 系统级通知 ---
  /** 系统通知 */
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  /** 系统告警 */
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  /** 班级公告 */
  CLASS_ANNOUNCEMENT = 'CLASS_ANNOUNCEMENT',
  /** 账号安全 */
  ACCOUNT_SECURITY = 'ACCOUNT_SECURITY',

  // --- 任务生命周期通知 ---
  /** 任务发布：老师布置并发布项目 */
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  /** 任务到期提醒：2天/1天到期提醒 */
  TASK_DUE_REMINDER = 'TASK_DUE_REMINDER',
  /** 任务逾期提醒 */
  TASK_OVERDUE = 'TASK_OVERDUE',
  /** 任务驳回：教师驳回学生作答 */
  TASK_REJECTED = 'TASK_REJECTED',
  /** 任务延期：教师为学生延期 */
  TASK_EXTENDED = 'TASK_EXTENDED',
  /** AI评分完成 */
  AI_GRADING_COMPLETED = 'AI_GRADING_COMPLETED',
  /** 答辩开启 */
  DEFENSE_OPENED = 'DEFENSE_OPENED',
  /** 未提交学生提醒（教师） */
  UNSUBMITTED_STUDENTS_ALERT = 'UNSUBMITTED_STUDENTS_ALERT',

  // --- 实践活动通知 ---
  /** 实践完成通知 */
  PRACTICE_COMPLETION_NOTIFICATION = 'PRACTICE_COMPLETION_NOTIFICATION',

  // --- 资源管理通知 ---
  /** Token使用预警 */
  TOKEN_USAGE_ALERT = 'TOKEN_USAGE_ALERT',

  // --- 成绩发布相关（三期新增） ---
  /** 成绩评分规则发布 */
  SCORE_RULE_PUBLISHED = 'SCORE_RULE_PUBLISHED',
  /** 成绩发布 */
  SCORE_PUBLISHED = 'SCORE_PUBLISHED',

  // --- 考试阅卷通知 ---
  /** 试卷扫描完成 */
  EXAM_SCAN_COMPLETED = 'EXAM_SCAN_COMPLETED',
  /** 试卷待复核 */
  EXAM_REVIEW_PENDING = 'EXAM_REVIEW_PENDING',
  /** 试卷成绩发布 */
  EXAM_SCORE_PUBLISHED = 'EXAM_SCORE_PUBLISHED',
  /** 试卷成绩撤回 */
  EXAM_SCORE_WITHDRAWN = 'EXAM_SCORE_WITHDRAWN',
  /** 试卷导出完成 */
  EXAM_EXPORT_COMPLETED = 'EXAM_EXPORT_COMPLETED',
  /** 试卷复核处理 */
  EXAM_GRADE_REVIEW_UPDATED = 'EXAM_GRADE_REVIEW_UPDATED',

  // --- 教学质量评价通知 ---
  /** 教学质量评价 AI 任务完成 */
  QUALITY_AI_TASK_COMPLETED = 'QUALITY_AI_TASK_COMPLETED',
  /** 教学质量评价 AI 任务失败 */
  QUALITY_AI_TASK_FAILED = 'QUALITY_AI_TASK_FAILED',
  /** 教学质量评价成绩导入完成 */
  QUALITY_SCORE_IMPORT_COMPLETED = 'QUALITY_SCORE_IMPORT_COMPLETED',
  /** 教学质量评价成绩导入失败 */
  QUALITY_SCORE_IMPORT_FAILED = 'QUALITY_SCORE_IMPORT_FAILED',
  /** 教学质量评价课程报告提交提醒 */
  QUALITY_COURSE_REPORT_REMINDER = 'QUALITY_COURSE_REPORT_REMINDER',
  /** 教学质量评价专业质量报告完成 */
  QUALITY_PROGRAM_REPORT_COMPLETED = 'QUALITY_PROGRAM_REPORT_COMPLETED',
  /** 教学质量评价持续改进任务分配 */
  QUALITY_IMPROVEMENT_TASK_ASSIGNED = 'QUALITY_IMPROVEMENT_TASK_ASSIGNED',
  /** 教学质量评价持续改进任务复评提醒 */
  QUALITY_IMPROVEMENT_TASK_REVIEW_REMINDER = 'QUALITY_IMPROVEMENT_TASK_REVIEW_REMINDER',
  /** 教学质量评价专家材料包导出完成 */
  QUALITY_EXPERT_PACKAGE_EXPORTED = 'QUALITY_EXPERT_PACKAGE_EXPORTED',
  /** 教学质量评价达成度审核流转 */
  QUALITY_ACHIEVEMENT_AUDIT_TRANSITED = 'QUALITY_ACHIEVEMENT_AUDIT_TRANSITED',
  /** 质量评价考核环节权重缺失 */
  QUALITY_MARK_ASSESSMENT_WEIGHT_MISSING = 'QUALITY_MARK_ASSESSMENT_WEIGHT_MISSING',

  // --- 重新提交申请相关（三期新增） ---
  /** 重新提交申请（发给指导老师） */
  RESUBMIT_REQUESTED = 'RESUBMIT_REQUESTED',
  /** 重新提交申请通过（发给学生） */
  RESUBMIT_APPROVED = 'RESUBMIT_APPROVED',
  /** 重新提交申请被拒（发给学生） */
  RESUBMIT_REJECTED = 'RESUBMIT_REJECTED',

  /** 教学档案袋档案审核退回 */
  PORTFOLIO_ARCHIVE_RETURNED = 'PORTFOLIO_ARCHIVE_RETURNED',
  /** 教学档案袋档案审核驳回 */
  PORTFOLIO_ARCHIVE_DISMISSED = 'PORTFOLIO_ARCHIVE_DISMISSED',
  /** 教学档案袋新教师建档欢迎 */
  PORTFOLIO_TEACHER_ONBOARDING = 'PORTFOLIO_TEACHER_ONBOARDING',
  /** 教学档案袋补采任务通知 */
  PORTFOLIO_GAP_TASK_PENDING = 'PORTFOLIO_GAP_TASK_PENDING',
  /** 教学档案袋补采生命周期暂停摘要 */
  PORTFOLIO_GAP_LIFECYCLE_SUSPENDED = 'PORTFOLIO_GAP_LIFECYCLE_SUSPENDED',
  /** 教学档案袋补采生命周期恢复摘要 */
  PORTFOLIO_GAP_LIFECYCLE_RESUMED = 'PORTFOLIO_GAP_LIFECYCLE_RESUMED',
  /** 教学档案袋审核生命周期挂起摘要 */
  PORTFOLIO_REVIEW_LIFECYCLE_SUSPENDED = 'PORTFOLIO_REVIEW_LIFECYCLE_SUSPENDED',
  /** 教学档案袋审核生命周期恢复摘要 */
  PORTFOLIO_REVIEW_LIFECYCLE_RESUMED = 'PORTFOLIO_REVIEW_LIFECYCLE_RESUMED',
  /** 教学档案袋评价材料确认 */
  PORTFOLIO_EVALUATION_MATERIAL_CONFIRM = 'PORTFOLIO_EVALUATION_MATERIAL_CONFIRM',
  /** 教学档案袋评价材料退回补充 */
  PORTFOLIO_EVALUATION_RETURNED_SUPPLEMENT = 'PORTFOLIO_EVALUATION_RETURNED_SUPPLEMENT',
  /** 教学档案袋评价材料已确认 */
  PORTFOLIO_EVALUATION_MATERIAL_CONFIRMED = 'PORTFOLIO_EVALUATION_MATERIAL_CONFIRMED',
  /** 教学档案袋评价结果公示 */
  PORTFOLIO_EVALUATION_PUBLICITY = 'PORTFOLIO_EVALUATION_PUBLICITY',
  /** 教学档案袋评价异议受理 */
  PORTFOLIO_EVALUATION_OBJECTION = 'PORTFOLIO_EVALUATION_OBJECTION',
  /** 教学档案袋评价异议复核结论 */
  PORTFOLIO_EVALUATION_OBJECTION_HANDLED = 'PORTFOLIO_EVALUATION_OBJECTION_HANDLED',
  /** 教学档案袋评价结果已归档 */
  PORTFOLIO_EVALUATION_ARCHIVED = 'PORTFOLIO_EVALUATION_ARCHIVED',
  /** 教学档案袋评价任务已关闭 */
  PORTFOLIO_EVALUATION_CLOSED = 'PORTFOLIO_EVALUATION_CLOSED',
  /** 教学档案袋评价任务已暂停 */
  PORTFOLIO_EVALUATION_SUSPENDED = 'PORTFOLIO_EVALUATION_SUSPENDED',
  /** 教学档案袋评价任务已恢复 */
  PORTFOLIO_EVALUATION_RESUMED = 'PORTFOLIO_EVALUATION_RESUMED',
  /** 教学档案袋评价生命周期暂停摘要 */
  PORTFOLIO_EVALUATION_LIFECYCLE_SUSPENDED = 'PORTFOLIO_EVALUATION_LIFECYCLE_SUSPENDED',
  /** 教学档案袋评价生命周期恢复摘要 */
  PORTFOLIO_EVALUATION_LIFECYCLE_RESUMED = 'PORTFOLIO_EVALUATION_LIFECYCLE_RESUMED',
  /** 教学档案袋评价阶段进展 */
  PORTFOLIO_EVALUATION_STAGE_SUBJECT = 'PORTFOLIO_EVALUATION_STAGE_SUBJECT',
  /** 教学档案袋评价阶段待办 */
  PORTFOLIO_EVALUATION_STAGE_REVIEWER = 'PORTFOLIO_EVALUATION_STAGE_REVIEWER',
  /** 教学档案袋评价任务已作废 */
  PORTFOLIO_EVALUATION_VOIDED = 'PORTFOLIO_EVALUATION_VOIDED',
  /** 教学档案袋评价任务已发布 */
  PORTFOLIO_EVALUATION_PUBLISHED = 'PORTFOLIO_EVALUATION_PUBLISHED',
  /** 教学档案袋评价材料全员已确认 */
  PORTFOLIO_EVALUATION_MATERIAL_ALL_CONFIRMED = 'PORTFOLIO_EVALUATION_MATERIAL_ALL_CONFIRMED',
  /** 教学档案袋评价材料确认齐套已打破 */
  PORTFOLIO_EVALUATION_MATERIAL_CONFIRM_BROKEN = 'PORTFOLIO_EVALUATION_MATERIAL_CONFIRM_BROKEN',
  /** 教学档案袋评价更正复核启动 */
  PORTFOLIO_EVALUATION_CORRECTION_STARTED = 'PORTFOLIO_EVALUATION_CORRECTION_STARTED',
  /** 教学档案袋评价更正复核完成 */
  PORTFOLIO_EVALUATION_CORRECTION_COMPLETED = 'PORTFOLIO_EVALUATION_CORRECTION_COMPLETED',
  /** 教学档案袋评价更正复核已撤销 */
  PORTFOLIO_EVALUATION_CORRECTION_CANCELLED = 'PORTFOLIO_EVALUATION_CORRECTION_CANCELLED',
  /** 教学档案袋评价更正复核工单已完成（非末单） */
  PORTFOLIO_EVALUATION_CORRECTION_ORDER_COMPLETED = 'PORTFOLIO_EVALUATION_CORRECTION_ORDER_COMPLETED',
  /** 教学档案袋评价公示期已结束 */
  PORTFOLIO_EVALUATION_PUBLICITY_EXPIRED = 'PORTFOLIO_EVALUATION_PUBLICITY_EXPIRED',
  /** 教学档案袋评价异议已全部办结 */
  PORTFOLIO_EVALUATION_OBJECTIONS_CLEARED = 'PORTFOLIO_EVALUATION_OBJECTIONS_CLEARED',
  /** 教学档案袋教师生命周期变更 */
  PORTFOLIO_TEACHER_LIFECYCLE_CHANGED = 'PORTFOLIO_TEACHER_LIFECYCLE_CHANGED',
  /** 教学档案袋规则变更通知 */
  PORTFOLIO_RULE_CHANGE = 'PORTFOLIO_RULE_CHANGE',
  /** 教学档案袋源修复重算完成 */
  PORTFOLIO_SOURCE_FIX_RECOMPUTE = 'PORTFOLIO_SOURCE_FIX_RECOMPUTE',
  /** 教学档案袋源修复重算告警待确认 */
  PORTFOLIO_SOURCE_FIX_ALERT_OPEN = 'PORTFOLIO_SOURCE_FIX_ALERT_OPEN',
  /** 教学档案袋双高阶段材料待审 */
  PORTFOLIO_DOUBLE_HIGH_STAGE_SUBMITTED = 'PORTFOLIO_DOUBLE_HIGH_STAGE_SUBMITTED',
  /** 教学档案袋双高阶段材料退回 */
  PORTFOLIO_DOUBLE_HIGH_STAGE_REJECTED = 'PORTFOLIO_DOUBLE_HIGH_STAGE_REJECTED',
  /** 教学档案袋双高阶段审核进行中 */
  PORTFOLIO_DOUBLE_HIGH_STAGE_REVIEW = 'PORTFOLIO_DOUBLE_HIGH_STAGE_REVIEW',
  /** 教学档案袋双高任务已作废 */
  PORTFOLIO_DOUBLE_HIGH_TASK_VOIDED = 'PORTFOLIO_DOUBLE_HIGH_TASK_VOIDED',
  /** 教学档案袋双高任务已归档 */
  PORTFOLIO_DOUBLE_HIGH_TASK_ARCHIVED = 'PORTFOLIO_DOUBLE_HIGH_TASK_ARCHIVED',
  /** 教学档案袋双师认定待院审 */
  PORTFOLIO_DUAL_TEACHER_COLLEGE_PENDING = 'PORTFOLIO_DUAL_TEACHER_COLLEGE_PENDING',
  /** 教学档案袋双师认定退回补正 */
  PORTFOLIO_DUAL_TEACHER_RETURNED = 'PORTFOLIO_DUAL_TEACHER_RETURNED',
  /** 教学档案袋双师认定待教务审 */
  PORTFOLIO_DUAL_TEACHER_ACADEMIC_PENDING = 'PORTFOLIO_DUAL_TEACHER_ACADEMIC_PENDING',
  /** 教学档案袋双师认定已通过 */
  PORTFOLIO_DUAL_TEACHER_APPROVED = 'PORTFOLIO_DUAL_TEACHER_APPROVED',
  /** 教学档案袋双师认定已驳回 */
  PORTFOLIO_DUAL_TEACHER_REJECTED = 'PORTFOLIO_DUAL_TEACHER_REJECTED',
  /** 教学档案袋职称申报待院审 */
  PORTFOLIO_TITLE_PROMOTION_COLLEGE_PENDING = 'PORTFOLIO_TITLE_PROMOTION_COLLEGE_PENDING',
  /** 教学档案袋职称申报退回补正 */
  PORTFOLIO_TITLE_PROMOTION_RETURNED = 'PORTFOLIO_TITLE_PROMOTION_RETURNED',
  /** 教学档案袋职称申报待人事复审 */
  PORTFOLIO_TITLE_PROMOTION_HR_PENDING = 'PORTFOLIO_TITLE_PROMOTION_HR_PENDING',
  /** 教学档案袋职称申报已驳回 */
  PORTFOLIO_TITLE_PROMOTION_REJECTED = 'PORTFOLIO_TITLE_PROMOTION_REJECTED',
  /** 教学档案袋职称申报进入公示 */
  PORTFOLIO_TITLE_PROMOTION_PUBLICITY = 'PORTFOLIO_TITLE_PROMOTION_PUBLICITY',
  /** 教学档案袋职称申报公示归档 */
  PORTFOLIO_TITLE_PROMOTION_ARCHIVED = 'PORTFOLIO_TITLE_PROMOTION_ARCHIVED',
  /** 教学档案袋职称申报待专家评审 */
  PORTFOLIO_TITLE_PROMOTION_EXPERT_PENDING = 'PORTFOLIO_TITLE_PROMOTION_EXPERT_PENDING',
  /** 教学档案袋外部专家评审授权待办 */
  PORTFOLIO_EXPERT_ASSIGNMENT_PENDING = 'PORTFOLIO_EXPERT_ASSIGNMENT_PENDING',
  /** 教学档案袋外部专家评审授权已吊销 */
  PORTFOLIO_EXPERT_ASSIGNMENT_REVOKED = 'PORTFOLIO_EXPERT_ASSIGNMENT_REVOKED',
  /** 教学档案袋外部专家评审授权已过期 */
  PORTFOLIO_EXPERT_ASSIGNMENT_EXPIRED = 'PORTFOLIO_EXPERT_ASSIGNMENT_EXPIRED',

  /** edu-mark 质量评价成绩同步失败 */
  MARK_QUALITY_SCORE_SYNC_FAILED = 'MARK_QUALITY_SCORE_SYNC_FAILED',
  /** 归档卷自动建卷失败 */
  MARK_ARCHIVE_AUTO_CREATE_FAILED = 'MARK_ARCHIVE_AUTO_CREATE_FAILED',
  /** 归档时限临近提醒 */
  MARK_ARCHIVE_DUE_UPCOMING = 'MARK_ARCHIVE_DUE_UPCOMING',
  /** 归档时限逾期提醒 */
  MARK_ARCHIVE_DUE_OVERDUE = 'MARK_ARCHIVE_DUE_OVERDUE',
  /** 保管到期鉴定提醒 */
  MARK_ARCHIVE_RETENTION_REMINDER = 'MARK_ARCHIVE_RETENTION_REMINDER',
  /** 延迟补交材料逾期提醒 */
  MARK_ARCHIVE_DELAY_SUBMISSION_OVERDUE = 'MARK_ARCHIVE_DELAY_SUBMISSION_OVERDUE',
  /** 查阅授权到期提醒 */
  MARK_ARCHIVE_ACCESS_EXPIRED = 'MARK_ARCHIVE_ACCESS_EXPIRED',
  /** 归档卷整改任务指派 */
  MARK_ARCHIVE_REMEDIATION_ASSIGNED = 'MARK_ARCHIVE_REMEDIATION_ASSIGNED',
  /** 归档卷整改材料已重提 */
  MARK_ARCHIVE_REMEDIATION_RESUBMITTED = 'MARK_ARCHIVE_REMEDIATION_RESUBMITTED',
  /** 归档卷收材驳回 */
  MARK_ARCHIVE_COLLECTION_REJECTED = 'MARK_ARCHIVE_COLLECTION_REJECTED',
  /** 归档卷待院系审核 */
  MARK_ARCHIVE_DEPARTMENT_REVIEW_REQUESTED = 'MARK_ARCHIVE_DEPARTMENT_REVIEW_REQUESTED',
  /** 归档卷院系审核通过 */
  MARK_ARCHIVE_DEPARTMENT_REVIEW_APPROVED = 'MARK_ARCHIVE_DEPARTMENT_REVIEW_APPROVED',
  /** 归档卷院系审核驳回 */
  MARK_ARCHIVE_DEPARTMENT_REVIEW_REJECTED = 'MARK_ARCHIVE_DEPARTMENT_REVIEW_REJECTED',
}
