import type { BadgeTone } from '@/components/ui-guide/ui/types'

/** 审计操作类型 */
export enum OperationTypeCode {
  SCORE_CHANGE = 'SCORE_CHANGE',
  SCORE_CONFIRM = 'SCORE_CONFIRM',
  SCORE_PUBLISH = 'SCORE_PUBLISH',
  SCORE_WITHDRAW = 'SCORE_WITHDRAW',
  REVIEW_REQUEST_HANDLE = 'REVIEW_REQUEST_HANDLE',
  GRADE_CORRECTION_CREATE = 'GRADE_CORRECTION_CREATE',
  QUALITY_OVERRIDE = 'QUALITY_OVERRIDE',
  ABSENCE_CONFIRM = 'ABSENCE_CONFIRM',
  ABSENCE_REVOKE = 'ABSENCE_REVOKE',
  ABSENCE_RECONCILE = 'ABSENCE_RECONCILE',
  DUPLICATE_RESOLVE = 'DUPLICATE_RESOLVE',
  BINDING_CONFIRM = 'BINDING_CONFIRM',
  DEANONYMIZE = 'DEANONYMIZE',
  REPAIR_SUBMIT = 'REPAIR_SUBMIT',
  SPOT_CHECK_ABNORMAL = 'SPOT_CHECK_ABNORMAL',
  BATCH_REPROCESS = 'BATCH_REPROCESS',
  GRADE_PASSBACK_EXECUTE = 'GRADE_PASSBACK_EXECUTE',
  GRADE_PASSBACK_RECONCILE = 'GRADE_PASSBACK_RECONCILE',
  GRADE_PASSBACK_CALLBACK = 'GRADE_PASSBACK_CALLBACK',
  SYNC_TASK_RETRY = 'SYNC_TASK_RETRY',
  SYNC_TASK_CANCEL = 'SYNC_TASK_CANCEL',
  EXPORT_CREATE = 'EXPORT_CREATE',
  EXPORT_START = 'EXPORT_START',
  EXPORT_COMPLETE = 'EXPORT_COMPLETE',
  EXPORT_FAIL = 'EXPORT_FAIL',
  ARCHIVE_CREATE = 'ARCHIVE_CREATE',
  ARCHIVE_PACKAGE_START = 'ARCHIVE_PACKAGE_START',
  ARCHIVE_PACKAGE_COMPLETE = 'ARCHIVE_PACKAGE_COMPLETE',
  ARCHIVE_PACKAGE_FAIL = 'ARCHIVE_PACKAGE_FAIL',
  ARCHIVE_APPRAISAL_REQUEST = 'ARCHIVE_APPRAISAL_REQUEST',
  ARCHIVE_APPRAISAL_DECIDE = 'ARCHIVE_APPRAISAL_DECIDE',
  ARCHIVE_RETENTION_EXTEND = 'ARCHIVE_RETENTION_EXTEND',
  ARCHIVE_DESTRUCTION_REQUEST = 'ARCHIVE_DESTRUCTION_REQUEST',
  ARCHIVE_DESTRUCTION_APPROVE = 'ARCHIVE_DESTRUCTION_APPROVE',
  ARCHIVE_DESTROY = 'ARCHIVE_DESTROY',
}

export const ALL_OPERATION_TYPE_CODES: readonly OperationTypeCode[] = [
  OperationTypeCode.SCORE_CHANGE,
  OperationTypeCode.SCORE_CONFIRM,
  OperationTypeCode.SCORE_PUBLISH,
  OperationTypeCode.SCORE_WITHDRAW,
  OperationTypeCode.REVIEW_REQUEST_HANDLE,
  OperationTypeCode.GRADE_CORRECTION_CREATE,
  OperationTypeCode.QUALITY_OVERRIDE,
  OperationTypeCode.ABSENCE_CONFIRM,
  OperationTypeCode.ABSENCE_REVOKE,
  OperationTypeCode.ABSENCE_RECONCILE,
  OperationTypeCode.DUPLICATE_RESOLVE,
  OperationTypeCode.BINDING_CONFIRM,
  OperationTypeCode.DEANONYMIZE,
  OperationTypeCode.REPAIR_SUBMIT,
  OperationTypeCode.SPOT_CHECK_ABNORMAL,
  OperationTypeCode.BATCH_REPROCESS,
  OperationTypeCode.GRADE_PASSBACK_EXECUTE,
  OperationTypeCode.GRADE_PASSBACK_RECONCILE,
  OperationTypeCode.GRADE_PASSBACK_CALLBACK,
  OperationTypeCode.SYNC_TASK_RETRY,
  OperationTypeCode.SYNC_TASK_CANCEL,
  OperationTypeCode.EXPORT_CREATE,
  OperationTypeCode.EXPORT_START,
  OperationTypeCode.EXPORT_COMPLETE,
  OperationTypeCode.EXPORT_FAIL,
  OperationTypeCode.ARCHIVE_CREATE,
  OperationTypeCode.ARCHIVE_PACKAGE_START,
  OperationTypeCode.ARCHIVE_PACKAGE_COMPLETE,
  OperationTypeCode.ARCHIVE_PACKAGE_FAIL,
  OperationTypeCode.ARCHIVE_APPRAISAL_REQUEST,
  OperationTypeCode.ARCHIVE_APPRAISAL_DECIDE,
  OperationTypeCode.ARCHIVE_RETENTION_EXTEND,
  OperationTypeCode.ARCHIVE_DESTRUCTION_REQUEST,
  OperationTypeCode.ARCHIVE_DESTRUCTION_APPROVE,
  OperationTypeCode.ARCHIVE_DESTROY,
]

export const OperationTypeDescription: Record<OperationTypeCode, string> = {
  [OperationTypeCode.SCORE_CHANGE]: '改分',
  [OperationTypeCode.SCORE_CONFIRM]: '成绩确认',
  [OperationTypeCode.SCORE_PUBLISH]: '成绩发布',
  [OperationTypeCode.SCORE_WITHDRAW]: '成绩撤回',
  [OperationTypeCode.REVIEW_REQUEST_HANDLE]: '复核申请处理',
  [OperationTypeCode.GRADE_CORRECTION_CREATE]: '成绩更正创建',
  [OperationTypeCode.QUALITY_OVERRIDE]: '质检覆盖',
  [OperationTypeCode.ABSENCE_CONFIRM]: '缺考确认',
  [OperationTypeCode.ABSENCE_REVOKE]: '缺考撤销',
  [OperationTypeCode.ABSENCE_RECONCILE]: '缺考核对',
  [OperationTypeCode.DUPLICATE_RESOLVE]: '重复处置',
  [OperationTypeCode.BINDING_CONFIRM]: '绑定确认',
  [OperationTypeCode.DEANONYMIZE]: '解匿名查看',
  [OperationTypeCode.REPAIR_SUBMIT]: '修复提交',
  [OperationTypeCode.SPOT_CHECK_ABNORMAL]: '抽检异常确认',
  [OperationTypeCode.BATCH_REPROCESS]: '异常批次重处理',
  [OperationTypeCode.GRADE_PASSBACK_EXECUTE]: '成绩回写执行',
  [OperationTypeCode.GRADE_PASSBACK_RECONCILE]: '成绩回写对账',
  [OperationTypeCode.GRADE_PASSBACK_CALLBACK]: '成绩回写外部回调',
  [OperationTypeCode.SYNC_TASK_RETRY]: '教务同步任务重试',
  [OperationTypeCode.SYNC_TASK_CANCEL]: '教务同步任务取消',
  [OperationTypeCode.EXPORT_CREATE]: '导出创建',
  [OperationTypeCode.EXPORT_START]: '导出开始',
  [OperationTypeCode.EXPORT_COMPLETE]: '导出完成',
  [OperationTypeCode.EXPORT_FAIL]: '导出失败',
  [OperationTypeCode.ARCHIVE_CREATE]: '考后归档创建',
  [OperationTypeCode.ARCHIVE_PACKAGE_START]: '考后归档打包开始',
  [OperationTypeCode.ARCHIVE_PACKAGE_COMPLETE]: '考后归档打包完成',
  [OperationTypeCode.ARCHIVE_PACKAGE_FAIL]: '考后归档打包失败',
  [OperationTypeCode.ARCHIVE_APPRAISAL_REQUEST]: '考后归档申请鉴定',
  [OperationTypeCode.ARCHIVE_APPRAISAL_DECIDE]: '考后归档鉴定决议',
  [OperationTypeCode.ARCHIVE_RETENTION_EXTEND]: '考后归档保管期限延长',
  [OperationTypeCode.ARCHIVE_DESTRUCTION_REQUEST]: '考后归档销毁申请',
  [OperationTypeCode.ARCHIVE_DESTRUCTION_APPROVE]: '考后归档销毁审批',
  [OperationTypeCode.ARCHIVE_DESTROY]: '考后归档销毁执行',
}

/** 审计操作类型展示色调：按成绩、质控、归档与失败语义分组 */
export const OPERATION_TYPE_TONE: Record<OperationTypeCode, BadgeTone> = {
  [OperationTypeCode.SCORE_CHANGE]: 'blue',
  [OperationTypeCode.SCORE_CONFIRM]: 'green',
  [OperationTypeCode.SCORE_PUBLISH]: 'green',
  [OperationTypeCode.SCORE_WITHDRAW]: 'red',
  [OperationTypeCode.REVIEW_REQUEST_HANDLE]: 'orange',
  [OperationTypeCode.GRADE_CORRECTION_CREATE]: 'orange',
  [OperationTypeCode.QUALITY_OVERRIDE]: 'orange',
  [OperationTypeCode.ABSENCE_CONFIRM]: 'orange',
  [OperationTypeCode.ABSENCE_REVOKE]: 'red',
  [OperationTypeCode.ABSENCE_RECONCILE]: 'blue',
  [OperationTypeCode.DUPLICATE_RESOLVE]: 'orange',
  [OperationTypeCode.BINDING_CONFIRM]: 'green',
  [OperationTypeCode.DEANONYMIZE]: 'orange',
  [OperationTypeCode.REPAIR_SUBMIT]: 'blue',
  [OperationTypeCode.SPOT_CHECK_ABNORMAL]: 'red',
  [OperationTypeCode.BATCH_REPROCESS]: 'red',
  [OperationTypeCode.GRADE_PASSBACK_EXECUTE]: 'blue',
  [OperationTypeCode.GRADE_PASSBACK_RECONCILE]: 'orange',
  [OperationTypeCode.GRADE_PASSBACK_CALLBACK]: 'green',
  [OperationTypeCode.SYNC_TASK_RETRY]: 'orange',
  [OperationTypeCode.SYNC_TASK_CANCEL]: 'red',
  [OperationTypeCode.EXPORT_CREATE]: 'blue',
  [OperationTypeCode.EXPORT_START]: 'blue',
  [OperationTypeCode.EXPORT_COMPLETE]: 'green',
  [OperationTypeCode.EXPORT_FAIL]: 'red',
  [OperationTypeCode.ARCHIVE_CREATE]: 'blue',
  [OperationTypeCode.ARCHIVE_PACKAGE_START]: 'blue',
  [OperationTypeCode.ARCHIVE_PACKAGE_COMPLETE]: 'green',
  [OperationTypeCode.ARCHIVE_PACKAGE_FAIL]: 'red',
  [OperationTypeCode.ARCHIVE_APPRAISAL_REQUEST]: 'purple',
  [OperationTypeCode.ARCHIVE_APPRAISAL_DECIDE]: 'purple',
  [OperationTypeCode.ARCHIVE_RETENTION_EXTEND]: 'blue',
  [OperationTypeCode.ARCHIVE_DESTRUCTION_REQUEST]: 'orange',
  [OperationTypeCode.ARCHIVE_DESTRUCTION_APPROVE]: 'orange',
  [OperationTypeCode.ARCHIVE_DESTROY]: 'red',
}

