/** PortfolioIndustryPackMajorCodeEnum */
export enum PortfolioIndustryPackMajorCode {
  AUTOMATION = 'AUTOMATION',
  AVIATION_NAVIGATION = 'AVIATION_NAVIGATION',
  CNC = 'CNC',
  COAL = 'COAL',
  COSMETICS = 'COSMETICS',
  ELECTRIC_POWER = 'ELECTRIC_POWER',
  ENERGY_SAVING_SAFETY = 'ENERGY_SAVING_SAFETY',
  FOOD = 'FOOD',
  INDUSTRIAL_ROBOT = 'INDUSTRIAL_ROBOT',
  INSPECTION_TESTING = 'INSPECTION_TESTING',
  INTELLIGENT_MANUFACTURING = 'INTELLIGENT_MANUFACTURING',
  INTELLIGENT_TRANSPORT = 'INTELLIGENT_TRANSPORT',
  LOGISTICS = 'LOGISTICS',
  MACHINERY = 'MACHINERY',
  MEDICAL_DEVICE = 'MEDICAL_DEVICE',
  MOLD = 'MOLD',
  NEW_ENERGY = 'NEW_ENERGY',
  PETROCHEMICAL = 'PETROCHEMICAL',
  PHARMACEUTICALS = 'PHARMACEUTICALS',
  RAIL_TRANSIT = 'RAIL_TRANSIT',
  ROAD_TRANSPORT = 'ROAD_TRANSPORT',
}

export const ALL_PortfolioIndustryPackMajor_CODES: readonly PortfolioIndustryPackMajorCode[] = [
  PortfolioIndustryPackMajorCode.AUTOMATION,
  PortfolioIndustryPackMajorCode.AVIATION_NAVIGATION,
  PortfolioIndustryPackMajorCode.CNC,
  PortfolioIndustryPackMajorCode.COAL,
  PortfolioIndustryPackMajorCode.COSMETICS,
  PortfolioIndustryPackMajorCode.ELECTRIC_POWER,
  PortfolioIndustryPackMajorCode.ENERGY_SAVING_SAFETY,
  PortfolioIndustryPackMajorCode.FOOD,
  PortfolioIndustryPackMajorCode.INDUSTRIAL_ROBOT,
  PortfolioIndustryPackMajorCode.INSPECTION_TESTING,
  PortfolioIndustryPackMajorCode.INTELLIGENT_MANUFACTURING,
  PortfolioIndustryPackMajorCode.INTELLIGENT_TRANSPORT,
  PortfolioIndustryPackMajorCode.LOGISTICS,
  PortfolioIndustryPackMajorCode.MACHINERY,
  PortfolioIndustryPackMajorCode.MEDICAL_DEVICE,
  PortfolioIndustryPackMajorCode.MOLD,
  PortfolioIndustryPackMajorCode.NEW_ENERGY,
  PortfolioIndustryPackMajorCode.PETROCHEMICAL,
  PortfolioIndustryPackMajorCode.PHARMACEUTICALS,
  PortfolioIndustryPackMajorCode.RAIL_TRANSIT,
  PortfolioIndustryPackMajorCode.ROAD_TRANSPORT,
]

export const PortfolioIndustryPackMajorCodeDescription: Record<PortfolioIndustryPackMajorCode, string> = {
  [PortfolioIndustryPackMajorCode.AUTOMATION]: '自动化',
  [PortfolioIndustryPackMajorCode.AVIATION_NAVIGATION]: '航空航海',
  [PortfolioIndustryPackMajorCode.CNC]: '数控',
  [PortfolioIndustryPackMajorCode.COAL]: '煤炭',
  [PortfolioIndustryPackMajorCode.COSMETICS]: '化妆品',
  [PortfolioIndustryPackMajorCode.ELECTRIC_POWER]: '电力',
  [PortfolioIndustryPackMajorCode.ENERGY_SAVING_SAFETY]: '节能与安全',
  [PortfolioIndustryPackMajorCode.FOOD]: '食品',
  [PortfolioIndustryPackMajorCode.INDUSTRIAL_ROBOT]: '工业机器人',
  [PortfolioIndustryPackMajorCode.INSPECTION_TESTING]: '检验检测',
  [PortfolioIndustryPackMajorCode.INTELLIGENT_MANUFACTURING]: '智能制造',
  [PortfolioIndustryPackMajorCode.INTELLIGENT_TRANSPORT]: '智能交通',
  [PortfolioIndustryPackMajorCode.LOGISTICS]: '物流',
  [PortfolioIndustryPackMajorCode.MACHINERY]: '机械',
  [PortfolioIndustryPackMajorCode.MEDICAL_DEVICE]: '医疗器械',
  [PortfolioIndustryPackMajorCode.MOLD]: '模具',
  [PortfolioIndustryPackMajorCode.NEW_ENERGY]: '新能源',
  [PortfolioIndustryPackMajorCode.PETROCHEMICAL]: '石油化工',
  [PortfolioIndustryPackMajorCode.PHARMACEUTICALS]: '药品',
  [PortfolioIndustryPackMajorCode.RAIL_TRANSIT]: '轨道交通',
  [PortfolioIndustryPackMajorCode.ROAD_TRANSPORT]: '道路运输',
}
