/** 审计资源类型 - PortfolioAuditResourceTypeEnum */
export enum PortfolioAuditResourceTypeCode {
  EXPORT_APPROVAL = 'EXPORT_APPROVAL',
  POLICY_DOCUMENT = 'POLICY_DOCUMENT',
  MASK_RULE = 'MASK_RULE',
  INTEGRATION_SYNC = 'INTEGRATION_SYNC',
  INTEGRATION_CONFLICT = 'INTEGRATION_CONFLICT',
  INTEGRATION_IDENTITY = 'INTEGRATION_IDENTITY',
  ALERT_RECORD = 'ALERT_RECORD',
  COMPLIANCE_ALERT = 'COMPLIANCE_ALERT',
  AI_TASK = 'AI_TASK',
  AI_ANALYSIS_RESULT = 'AI_ANALYSIS_RESULT',
  PRIVACY_CONSENT = 'PRIVACY_CONSENT',
  TEACHER_PK_SESSION = 'TEACHER_PK_SESSION',
  CORRECTION_IMPACT = 'CORRECTION_IMPACT',
  SOURCE_FIX_EVENT = 'SOURCE_FIX_EVENT',
  PLANNING_SYNC_CONFIG = 'PLANNING_SYNC_CONFIG',
  HISTORY_PLAN_IMPORT_BATCH = 'HISTORY_PLAN_IMPORT_BATCH',
  REPORTING_TASK = 'REPORTING_TASK',
  NATIONAL_REPORT_BATCH = 'NATIONAL_REPORT_BATCH',
  TITLE_CRITERIA_TEMPLATE = 'TITLE_CRITERIA_TEMPLATE',
  TITLE_TASK_CRITERIA = 'TITLE_TASK_CRITERIA',
  TITLE_APPLICATION = 'TITLE_APPLICATION',
  TITLE_TASK_CRITERIA_CHANGE = 'TITLE_TASK_CRITERIA_CHANGE',
  ETHICS_SANCTION = 'ETHICS_SANCTION',
  RULE_PUBLISH_SNAPSHOT = 'RULE_PUBLISH_SNAPSHOT',
  RULE_IMPACT_REPORT = 'RULE_IMPACT_REPORT',
  EVALUATION_TASK = 'EVALUATION_TASK',
}

export const ALL_PORTFOLIO_AUDIT_RESOURCE_TYPE_CODES = Object.values(
  PortfolioAuditResourceTypeCode,
) as PortfolioAuditResourceTypeCode[]

export const PortfolioAuditResourceTypeDescription: Record<PortfolioAuditResourceTypeCode, string> = {
  [PortfolioAuditResourceTypeCode.EXPORT_APPROVAL]: '导出审批',
  [PortfolioAuditResourceTypeCode.POLICY_DOCUMENT]: '政策文件',
  [PortfolioAuditResourceTypeCode.MASK_RULE]: '脱敏规则',
  [PortfolioAuditResourceTypeCode.INTEGRATION_SYNC]: '集成同步',
  [PortfolioAuditResourceTypeCode.INTEGRATION_CONFLICT]: '集成冲突单',
  [PortfolioAuditResourceTypeCode.INTEGRATION_IDENTITY]: '身份待匹配',
  [PortfolioAuditResourceTypeCode.ALERT_RECORD]: '画像预警',
  [PortfolioAuditResourceTypeCode.COMPLIANCE_ALERT]: '结构合规预警',
  [PortfolioAuditResourceTypeCode.AI_TASK]: 'AI 任务',
  [PortfolioAuditResourceTypeCode.AI_ANALYSIS_RESULT]: 'AI 分析结果',
  [PortfolioAuditResourceTypeCode.PRIVACY_CONSENT]: '个人信息处理同意',
  [PortfolioAuditResourceTypeCode.TEACHER_PK_SESSION]: '教师 PK 对比会话',
  [PortfolioAuditResourceTypeCode.CORRECTION_IMPACT]: '纠错影响报告',
  [PortfolioAuditResourceTypeCode.SOURCE_FIX_EVENT]: '源修复重算事件',
  [PortfolioAuditResourceTypeCode.PLANNING_SYNC_CONFIG]: '历史规划同步设置',
  [PortfolioAuditResourceTypeCode.HISTORY_PLAN_IMPORT_BATCH]: '历史规划导入批次',
  [PortfolioAuditResourceTypeCode.REPORTING_TASK]: '上级报送任务',
  [PortfolioAuditResourceTypeCode.NATIONAL_REPORT_BATCH]: '全国教师上报批次',
  [PortfolioAuditResourceTypeCode.TITLE_CRITERIA_TEMPLATE]: '职称资格条件模板',
  [PortfolioAuditResourceTypeCode.TITLE_TASK_CRITERIA]: '职称任务资格条件',
  [PortfolioAuditResourceTypeCode.TITLE_APPLICATION]: '职称申报申请',
  [PortfolioAuditResourceTypeCode.TITLE_TASK_CRITERIA_CHANGE]: '职称任务条件紧急修正',
  [PortfolioAuditResourceTypeCode.ETHICS_SANCTION]: '师德处分',
  [PortfolioAuditResourceTypeCode.RULE_PUBLISH_SNAPSHOT]: '规则发布快照',
  [PortfolioAuditResourceTypeCode.RULE_IMPACT_REPORT]: '规则发布影响分析',
  [PortfolioAuditResourceTypeCode.EVALUATION_TASK]: '多元评价任务',
}
