/** PortfolioIndustryPackDictCategoryCodeEnum */
export enum PortfolioIndustryPackDictCategoryCode {
  CNC_MACHINING_PRACTICE = 'CNC_MACHINING_PRACTICE',
  CNC_SKILL_LEVEL = 'CNC_SKILL_LEVEL',
  DISPATCHER_CERT = 'DISPATCHER_CERT',
  DISPATCH_CENTER_PRACTICE = 'DISPATCH_CENTER_PRACTICE',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  DRUG_REGULATION_PRACTICE = 'DRUG_REGULATION_PRACTICE',
  ELECTRICIAN_CERT = 'ELECTRICIAN_CERT',
  ENERGY_ENTERPRISE_INTERNSHIP = 'ENERGY_ENTERPRISE_INTERNSHIP',
  ENERGY_MANAGER = 'ENERGY_MANAGER',
  ENERGY_SAVING_PROJECT = 'ENERGY_SAVING_PROJECT',
  EQUIPMENT_MFG_ENTERPRISE_PRACTICE = 'EQUIPMENT_MFG_ENTERPRISE_PRACTICE',
  FIXTURE_AND_LINE_PROJECT = 'FIXTURE_AND_LINE_PROJECT',
  FOOD_SAFETY_MANAGER = 'FOOD_SAFETY_MANAGER',
  FOOD_SAFETY_PRACTICE = 'FOOD_SAFETY_PRACTICE',
  GMP_ENTERPRISE_PRACTICE = 'GMP_ENTERPRISE_PRACTICE',
  GSP_ENTERPRISE_PRACTICE = 'GSP_ENTERPRISE_PRACTICE',
  HORIZONTAL_PROJECT = 'HORIZONTAL_PROJECT',
  INDUSTRIAL_ROBOT_OPERATOR_CERT = 'INDUSTRIAL_ROBOT_OPERATOR_CERT',
  INDUSTRY_COMPETITION_SUPPORT = 'INDUSTRY_COMPETITION_SUPPORT',
  INDUSTRY_EDUCATION_PROJECT = 'INDUSTRY_EDUCATION_PROJECT',
  INSPECTOR = 'INSPECTOR',
  LICENSED_PHARMACIST = 'LICENSED_PHARMACIST',
  LOGISTICS_HUB_PRACTICE = 'LOGISTICS_HUB_PRACTICE',
  LOGISTICS_SPECIALIST = 'LOGISTICS_SPECIALIST',
  MEDICAL_DEVICE_QM = 'MEDICAL_DEVICE_QM',
  MODERN_APPRENTICESHIP_ORDER_CLASS = 'MODERN_APPRENTICESHIP_ORDER_CLASS',
  MODERN_APPRENTICESHIP_POST_PRACTICE = 'MODERN_APPRENTICESHIP_POST_PRACTICE',
  NEW_ENERGY_STATION_PRACTICE = 'NEW_ENERGY_STATION_PRACTICE',
  PETROCHEMICAL_UNIT_PRACTICE = 'PETROCHEMICAL_UNIT_PRACTICE',
  POWER_PLANT_OPS_PRACTICE = 'POWER_PLANT_OPS_PRACTICE',
  PRODUCTION_LINE_OPS_PRACTICE = 'PRODUCTION_LINE_OPS_PRACTICE',
  RAIL_TRANSIT_OPS_CERT = 'RAIL_TRANSIT_OPS_CERT',
  REGISTERED_SAFETY_ENGINEER = 'REGISTERED_SAFETY_ENGINEER',
  SAFETY_SOCIAL_SERVICE = 'SAFETY_SOCIAL_SERVICE',
  SCHOOL_ENTERPRISE_TRAINING_LINE = 'SCHOOL_ENTERPRISE_TRAINING_LINE',
  SKILL_COMPETITION_SUPPORT = 'SKILL_COMPETITION_SUPPORT',
  SMART_TRANSPORT_PROJECT = 'SMART_TRANSPORT_PROJECT',
  SPECIAL_OPERATION_CERT = 'SPECIAL_OPERATION_CERT',
  STATION_OPS_PRACTICE = 'STATION_OPS_PRACTICE',
  TECH_SERVICE_AND_HORIZONTAL = 'TECH_SERVICE_AND_HORIZONTAL',
  TECH_SERVICE_AND_STANDARD = 'TECH_SERVICE_AND_STANDARD',
  TECH_SERVICE_PROJECT = 'TECH_SERVICE_PROJECT',
  TRAINING_AND_SIMULATION = 'TRAINING_AND_SIMULATION',
  TRAINING_BASE_PROJECT = 'TRAINING_BASE_PROJECT',
  TRANSPORT_ENTERPRISE_PRACTICE = 'TRANSPORT_ENTERPRISE_PRACTICE',
  TRANSPORT_TECH_SERVICE = 'TRANSPORT_TECH_SERVICE',
  WELDER_CERT = 'WELDER_CERT',
}

export const ALL_PortfolioIndustryPackDictCategory_CODES: readonly PortfolioIndustryPackDictCategoryCode[] = [
  PortfolioIndustryPackDictCategoryCode.CNC_MACHINING_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.CNC_SKILL_LEVEL,
  PortfolioIndustryPackDictCategoryCode.DISPATCHER_CERT,
  PortfolioIndustryPackDictCategoryCode.DISPATCH_CENTER_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.DRIVING_LICENSE,
  PortfolioIndustryPackDictCategoryCode.DRUG_REGULATION_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.ELECTRICIAN_CERT,
  PortfolioIndustryPackDictCategoryCode.ENERGY_ENTERPRISE_INTERNSHIP,
  PortfolioIndustryPackDictCategoryCode.ENERGY_MANAGER,
  PortfolioIndustryPackDictCategoryCode.ENERGY_SAVING_PROJECT,
  PortfolioIndustryPackDictCategoryCode.EQUIPMENT_MFG_ENTERPRISE_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.FIXTURE_AND_LINE_PROJECT,
  PortfolioIndustryPackDictCategoryCode.FOOD_SAFETY_MANAGER,
  PortfolioIndustryPackDictCategoryCode.FOOD_SAFETY_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.GMP_ENTERPRISE_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.GSP_ENTERPRISE_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.HORIZONTAL_PROJECT,
  PortfolioIndustryPackDictCategoryCode.INDUSTRIAL_ROBOT_OPERATOR_CERT,
  PortfolioIndustryPackDictCategoryCode.INDUSTRY_COMPETITION_SUPPORT,
  PortfolioIndustryPackDictCategoryCode.INDUSTRY_EDUCATION_PROJECT,
  PortfolioIndustryPackDictCategoryCode.INSPECTOR,
  PortfolioIndustryPackDictCategoryCode.LICENSED_PHARMACIST,
  PortfolioIndustryPackDictCategoryCode.LOGISTICS_HUB_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.LOGISTICS_SPECIALIST,
  PortfolioIndustryPackDictCategoryCode.MEDICAL_DEVICE_QM,
  PortfolioIndustryPackDictCategoryCode.MODERN_APPRENTICESHIP_ORDER_CLASS,
  PortfolioIndustryPackDictCategoryCode.MODERN_APPRENTICESHIP_POST_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.NEW_ENERGY_STATION_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.PETROCHEMICAL_UNIT_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.POWER_PLANT_OPS_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.PRODUCTION_LINE_OPS_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.RAIL_TRANSIT_OPS_CERT,
  PortfolioIndustryPackDictCategoryCode.REGISTERED_SAFETY_ENGINEER,
  PortfolioIndustryPackDictCategoryCode.SAFETY_SOCIAL_SERVICE,
  PortfolioIndustryPackDictCategoryCode.SCHOOL_ENTERPRISE_TRAINING_LINE,
  PortfolioIndustryPackDictCategoryCode.SKILL_COMPETITION_SUPPORT,
  PortfolioIndustryPackDictCategoryCode.SMART_TRANSPORT_PROJECT,
  PortfolioIndustryPackDictCategoryCode.SPECIAL_OPERATION_CERT,
  PortfolioIndustryPackDictCategoryCode.STATION_OPS_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_AND_HORIZONTAL,
  PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_AND_STANDARD,
  PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_PROJECT,
  PortfolioIndustryPackDictCategoryCode.TRAINING_AND_SIMULATION,
  PortfolioIndustryPackDictCategoryCode.TRAINING_BASE_PROJECT,
  PortfolioIndustryPackDictCategoryCode.TRANSPORT_ENTERPRISE_PRACTICE,
  PortfolioIndustryPackDictCategoryCode.TRANSPORT_TECH_SERVICE,
  PortfolioIndustryPackDictCategoryCode.WELDER_CERT,
]

export const PortfolioIndustryPackDictCategoryCodeDescription: Record<PortfolioIndustryPackDictCategoryCode, string> = {
  [PortfolioIndustryPackDictCategoryCode.CNC_MACHINING_PRACTICE]: '数控加工实践',
  [PortfolioIndustryPackDictCategoryCode.CNC_SKILL_LEVEL]: '数控技能等级',
  [PortfolioIndustryPackDictCategoryCode.DISPATCHER_CERT]: '调度员证',
  [PortfolioIndustryPackDictCategoryCode.DISPATCH_CENTER_PRACTICE]: '调度中心实践',
  [PortfolioIndustryPackDictCategoryCode.DRIVING_LICENSE]: '驾驶证',
  [PortfolioIndustryPackDictCategoryCode.DRUG_REGULATION_PRACTICE]: '药监类实践',
  [PortfolioIndustryPackDictCategoryCode.ELECTRICIAN_CERT]: '电工证',
  [PortfolioIndustryPackDictCategoryCode.ENERGY_ENTERPRISE_INTERNSHIP]: '能源企业顶岗实践',
  [PortfolioIndustryPackDictCategoryCode.ENERGY_MANAGER]: '能源管理师',
  [PortfolioIndustryPackDictCategoryCode.ENERGY_SAVING_PROJECT]: '节能改造项目',
  [PortfolioIndustryPackDictCategoryCode.EQUIPMENT_MFG_ENTERPRISE_PRACTICE]: '装备制造企业实践',
  [PortfolioIndustryPackDictCategoryCode.FIXTURE_AND_LINE_PROJECT]: '工装夹具与产线项目',
  [PortfolioIndustryPackDictCategoryCode.FOOD_SAFETY_MANAGER]: '食品安全管理师',
  [PortfolioIndustryPackDictCategoryCode.FOOD_SAFETY_PRACTICE]: '食安类实践',
  [PortfolioIndustryPackDictCategoryCode.GMP_ENTERPRISE_PRACTICE]: 'GMP企业实践',
  [PortfolioIndustryPackDictCategoryCode.GSP_ENTERPRISE_PRACTICE]: 'GSP企业实践',
  [PortfolioIndustryPackDictCategoryCode.HORIZONTAL_PROJECT]: '横向课题',
  [PortfolioIndustryPackDictCategoryCode.INDUSTRIAL_ROBOT_OPERATOR_CERT]: '工业机器人操作证',
  [PortfolioIndustryPackDictCategoryCode.INDUSTRY_COMPETITION_SUPPORT]: '行业竞赛支撑',
  [PortfolioIndustryPackDictCategoryCode.INDUSTRY_EDUCATION_PROJECT]: '产教融合项目',
  [PortfolioIndustryPackDictCategoryCode.INSPECTOR]: '检验员',
  [PortfolioIndustryPackDictCategoryCode.LICENSED_PHARMACIST]: '执业药师',
  [PortfolioIndustryPackDictCategoryCode.LOGISTICS_HUB_PRACTICE]: '物流枢纽实践',
  [PortfolioIndustryPackDictCategoryCode.LOGISTICS_SPECIALIST]: '物流师',
  [PortfolioIndustryPackDictCategoryCode.MEDICAL_DEVICE_QM]: '医疗器械质量管理师',
  [PortfolioIndustryPackDictCategoryCode.MODERN_APPRENTICESHIP_ORDER_CLASS]: '现代学徒制订单班',
  [PortfolioIndustryPackDictCategoryCode.MODERN_APPRENTICESHIP_POST_PRACTICE]: '现代学徒制岗位实践',
  [PortfolioIndustryPackDictCategoryCode.NEW_ENERGY_STATION_PRACTICE]: '新能源场站实践',
  [PortfolioIndustryPackDictCategoryCode.PETROCHEMICAL_UNIT_PRACTICE]: '石化装置实践',
  [PortfolioIndustryPackDictCategoryCode.POWER_PLANT_OPS_PRACTICE]: '电厂运维实践',
  [PortfolioIndustryPackDictCategoryCode.PRODUCTION_LINE_OPS_PRACTICE]: '产线运维实践',
  [PortfolioIndustryPackDictCategoryCode.RAIL_TRANSIT_OPS_CERT]: '轨道交通运维证',
  [PortfolioIndustryPackDictCategoryCode.REGISTERED_SAFETY_ENGINEER]: '注册安全工程师',
  [PortfolioIndustryPackDictCategoryCode.SAFETY_SOCIAL_SERVICE]: '安全生产社会服务',
  [PortfolioIndustryPackDictCategoryCode.SCHOOL_ENTERPRISE_TRAINING_LINE]: '校企共建实训线路',
  [PortfolioIndustryPackDictCategoryCode.SKILL_COMPETITION_SUPPORT]: '技能大赛支撑',
  [PortfolioIndustryPackDictCategoryCode.SMART_TRANSPORT_PROJECT]: '智慧交通项目',
  [PortfolioIndustryPackDictCategoryCode.SPECIAL_OPERATION_CERT]: '特种作业操作证',
  [PortfolioIndustryPackDictCategoryCode.STATION_OPS_PRACTICE]: '场站运维实践',
  [PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_AND_HORIZONTAL]: '技术服务与横向课题',
  [PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_AND_STANDARD]: '技术服务与标准制定',
  [PortfolioIndustryPackDictCategoryCode.TECH_SERVICE_PROJECT]: '技术服务项目',
  [PortfolioIndustryPackDictCategoryCode.TRAINING_AND_SIMULATION]: '实训与仿真教学',
  [PortfolioIndustryPackDictCategoryCode.TRAINING_BASE_PROJECT]: '实训基地项目',
  [PortfolioIndustryPackDictCategoryCode.TRANSPORT_ENTERPRISE_PRACTICE]: '运输企业实践',
  [PortfolioIndustryPackDictCategoryCode.TRANSPORT_TECH_SERVICE]: '交通技术服务',
  [PortfolioIndustryPackDictCategoryCode.WELDER_CERT]: '焊工证',
}
