/** 导出类型 - PortfolioExportTypeEnum */
export enum PortfolioExportTypeCode {
  MAJOR_GROUP_PORTFOLIO = 'MAJOR_GROUP_PORTFOLIO',
  DEPARTMENT_REPORT = 'DEPARTMENT_REPORT',
  TEACHER_ARCHIVE = 'TEACHER_ARCHIVE',
  ANALYSIS_REPORT = 'ANALYSIS_REPORT',
  MAJOR_GROUP_MATERIAL_PACKAGE = 'MAJOR_GROUP_MATERIAL_PACKAGE',
  DOUBLE_HIGH_ACCEPTANCE_PACKAGE = 'DOUBLE_HIGH_ACCEPTANCE_PACKAGE',
  MATERIAL_PACKAGE = 'MATERIAL_PACKAGE',
  NATIONAL_TEACHER_REPORT = 'NATIONAL_TEACHER_REPORT',
  NATIONAL_TEACHER_REPORT_RETRANSMIT = 'NATIONAL_TEACHER_REPORT_RETRANSMIT',
  SUPERIOR_REPORTING = 'SUPERIOR_REPORTING',
  TEACHER_PK_COMPARE = 'TEACHER_PK_COMPARE',
  TEACHER_TRANSFER_PACKAGE = 'TEACHER_TRANSFER_PACKAGE',
  TEACHER_TRANSFER_IMPORT = 'TEACHER_TRANSFER_IMPORT',
  DUAL_TEACHER_ROSTER = 'DUAL_TEACHER_ROSTER',
  TEACHER_ROSTER = 'TEACHER_ROSTER',
  KEY_TEACHER_ROSTER = 'KEY_TEACHER_ROSTER',
  EXTERNAL_TEACHER_ROSTER = 'EXTERNAL_TEACHER_ROSTER',
  DOUBLE_DUTY_ROSTER = 'DOUBLE_DUTY_ROSTER',
  TEACHER_SALARY = 'TEACHER_SALARY',
  TEACHER_LIBRARY_BORROW = 'TEACHER_LIBRARY_BORROW',
  DEVELOPMENT_RECORD = 'DEVELOPMENT_RECORD',
  DEVELOPMENT_PLAN = 'DEVELOPMENT_PLAN',
  EVALUATION_TASK = 'EVALUATION_TASK',
  EVALUATION_PUBLICITY = 'EVALUATION_PUBLICITY',
  EVALUATION_OBJECTION = 'EVALUATION_OBJECTION',
  EVALUATION_SUMMARY = 'EVALUATION_SUMMARY',
  EVALUATION_COMPREHENSIVE_ANALYSIS = 'EVALUATION_COMPREHENSIVE_ANALYSIS',
  TEACHER_ONE_TABLE = 'TEACHER_ONE_TABLE',
  DEPT_ONE_TABLE = 'DEPT_ONE_TABLE',
}

/** 可走导出审批申请的类型子集 */
export const ALL_PORTFOLIO_EXPORT_APPROVAL_TYPE_CODES: readonly PortfolioExportTypeCode[] = [
  PortfolioExportTypeCode.MAJOR_GROUP_PORTFOLIO,
  PortfolioExportTypeCode.DEPARTMENT_REPORT,
  PortfolioExportTypeCode.TEACHER_ARCHIVE,
  PortfolioExportTypeCode.ANALYSIS_REPORT,
  PortfolioExportTypeCode.DUAL_TEACHER_ROSTER,
  PortfolioExportTypeCode.NATIONAL_TEACHER_REPORT,
  PortfolioExportTypeCode.TEACHER_TRANSFER_PACKAGE,
  PortfolioExportTypeCode.TEACHER_ROSTER,
  PortfolioExportTypeCode.KEY_TEACHER_ROSTER,
  PortfolioExportTypeCode.EXTERNAL_TEACHER_ROSTER,
  PortfolioExportTypeCode.DOUBLE_DUTY_ROSTER,
  PortfolioExportTypeCode.TEACHER_SALARY,
  PortfolioExportTypeCode.TEACHER_LIBRARY_BORROW,
  PortfolioExportTypeCode.DEVELOPMENT_RECORD,
  PortfolioExportTypeCode.DEVELOPMENT_PLAN,
  PortfolioExportTypeCode.EVALUATION_TASK,
  PortfolioExportTypeCode.EVALUATION_PUBLICITY,
  PortfolioExportTypeCode.EVALUATION_OBJECTION,
  PortfolioExportTypeCode.EVALUATION_SUMMARY,
  PortfolioExportTypeCode.EVALUATION_COMPREHENSIVE_ANALYSIS,
  PortfolioExportTypeCode.TEACHER_PK_COMPARE,
  PortfolioExportTypeCode.TEACHER_ONE_TABLE,
  PortfolioExportTypeCode.DEPT_ONE_TABLE,
]

export const ALL_PORTFOLIO_EXPORT_TYPE_CODES: readonly PortfolioExportTypeCode[] = [
  PortfolioExportTypeCode.MAJOR_GROUP_PORTFOLIO,
  PortfolioExportTypeCode.DEPARTMENT_REPORT,
  PortfolioExportTypeCode.TEACHER_ARCHIVE,
  PortfolioExportTypeCode.ANALYSIS_REPORT,
  PortfolioExportTypeCode.MAJOR_GROUP_MATERIAL_PACKAGE,
  PortfolioExportTypeCode.DOUBLE_HIGH_ACCEPTANCE_PACKAGE,
  PortfolioExportTypeCode.MATERIAL_PACKAGE,
  PortfolioExportTypeCode.NATIONAL_TEACHER_REPORT,
  PortfolioExportTypeCode.NATIONAL_TEACHER_REPORT_RETRANSMIT,
  PortfolioExportTypeCode.SUPERIOR_REPORTING,
  PortfolioExportTypeCode.TEACHER_PK_COMPARE,
  PortfolioExportTypeCode.TEACHER_TRANSFER_PACKAGE,
  PortfolioExportTypeCode.TEACHER_TRANSFER_IMPORT,
  PortfolioExportTypeCode.DUAL_TEACHER_ROSTER,
  PortfolioExportTypeCode.TEACHER_ROSTER,
  PortfolioExportTypeCode.KEY_TEACHER_ROSTER,
  PortfolioExportTypeCode.EXTERNAL_TEACHER_ROSTER,
  PortfolioExportTypeCode.DOUBLE_DUTY_ROSTER,
  PortfolioExportTypeCode.TEACHER_SALARY,
  PortfolioExportTypeCode.TEACHER_LIBRARY_BORROW,
  PortfolioExportTypeCode.DEVELOPMENT_RECORD,
  PortfolioExportTypeCode.DEVELOPMENT_PLAN,
  PortfolioExportTypeCode.EVALUATION_TASK,
  PortfolioExportTypeCode.EVALUATION_PUBLICITY,
  PortfolioExportTypeCode.EVALUATION_OBJECTION,
  PortfolioExportTypeCode.EVALUATION_SUMMARY,
  PortfolioExportTypeCode.EVALUATION_COMPREHENSIVE_ANALYSIS,
  PortfolioExportTypeCode.TEACHER_ONE_TABLE,
  PortfolioExportTypeCode.DEPT_ONE_TABLE,
]

export const PortfolioExportTypeDescription: Record<PortfolioExportTypeCode, string> = {
  [PortfolioExportTypeCode.MAJOR_GROUP_PORTFOLIO]: '专业群档案袋',
  [PortfolioExportTypeCode.DEPARTMENT_REPORT]: '院系报告',
  [PortfolioExportTypeCode.TEACHER_ARCHIVE]: '教师档案包',
  [PortfolioExportTypeCode.ANALYSIS_REPORT]: '分析报告',
  [PortfolioExportTypeCode.MAJOR_GROUP_MATERIAL_PACKAGE]: '专业群教学档案袋材料包',
  [PortfolioExportTypeCode.DOUBLE_HIGH_ACCEPTANCE_PACKAGE]: '双高建设任务验收材料包',
  [PortfolioExportTypeCode.MATERIAL_PACKAGE]: '档案材料包',
  [PortfolioExportTypeCode.NATIONAL_TEACHER_REPORT]: '国家级教师报表',
  [PortfolioExportTypeCode.NATIONAL_TEACHER_REPORT_RETRANSMIT]: '国家级教师报表重传',
  [PortfolioExportTypeCode.SUPERIOR_REPORTING]: '上级报送',
  [PortfolioExportTypeCode.TEACHER_PK_COMPARE]: '教师 PK 对比',
  [PortfolioExportTypeCode.TEACHER_TRANSFER_PACKAGE]: '教师迁出数据包',
  [PortfolioExportTypeCode.TEACHER_TRANSFER_IMPORT]: '教师迁出数据导入',
  [PortfolioExportTypeCode.DUAL_TEACHER_ROSTER]: '双师认定台账',
  [PortfolioExportTypeCode.TEACHER_ROSTER]: '教师名册',
  [PortfolioExportTypeCode.KEY_TEACHER_ROSTER]: '骨干教师/专业带头人台账',
  [PortfolioExportTypeCode.EXTERNAL_TEACHER_ROSTER]: '外聘教师台账',
  [PortfolioExportTypeCode.DOUBLE_DUTY_ROSTER]: '双肩挑台账',
  [PortfolioExportTypeCode.TEACHER_SALARY]: '教师薪酬台账',
  [PortfolioExportTypeCode.TEACHER_LIBRARY_BORROW]: '教师图书借阅台账',
  [PortfolioExportTypeCode.DEVELOPMENT_RECORD]: '发展档案台账',
  [PortfolioExportTypeCode.DEVELOPMENT_PLAN]: '发展规划台账',
  [PortfolioExportTypeCode.EVALUATION_TASK]: '多元评价任务台账',
  [PortfolioExportTypeCode.EVALUATION_PUBLICITY]: '评价公示台账',
  [PortfolioExportTypeCode.EVALUATION_OBJECTION]: '评价异议台账',
  [PortfolioExportTypeCode.EVALUATION_SUMMARY]: '评价填报汇总',
  [PortfolioExportTypeCode.EVALUATION_COMPREHENSIVE_ANALYSIS]: '多元评价综合分析',
  [PortfolioExportTypeCode.TEACHER_ONE_TABLE]: '教师一张表',
  [PortfolioExportTypeCode.DEPT_ONE_TABLE]: '部门一张表',
}
