/** 参评材料分类身份类 - PortfolioIdentityMaterialCategoryClassEnum */
export enum PortfolioIdentityMaterialCategoryClassCode {
  DOCUMENT = 'DOCUMENT',
  TITLE = 'TITLE',
  DEGREE = 'DEGREE',
  ETHICS = 'ETHICS',
  QUALIFICATION = 'QUALIFICATION',
  APPOINTMENT = 'APPOINTMENT',
  BASIC = 'BASIC',
  PROFILE = 'PROFILE',
  EXTERNAL = 'EXTERNAL',
  INDUSTRY_MENTOR = 'INDUSTRY_MENTOR',
  ENTERPRISE_PART = 'ENTERPRISE_PART',
  SKILL_MASTER = 'SKILL_MASTER',
  CRAFTSMAN = 'CRAFTSMAN',
  TEACHING = 'TEACHING',
  RESEARCH = 'RESEARCH',
  HONOR = 'HONOR',
  ACHIEVEMENT = 'ACHIEVEMENT',
}

export const PortfolioIdentityMaterialCategoryClassDescription: Record<PortfolioIdentityMaterialCategoryClassCode, string> = {
  [PortfolioIdentityMaterialCategoryClassCode.DOCUMENT]: '基础文档',
  [PortfolioIdentityMaterialCategoryClassCode.TITLE]: '职称材料',
  [PortfolioIdentityMaterialCategoryClassCode.DEGREE]: '学历学位',
  [PortfolioIdentityMaterialCategoryClassCode.ETHICS]: '师德师风',
  [PortfolioIdentityMaterialCategoryClassCode.QUALIFICATION]: '资格资质',
  [PortfolioIdentityMaterialCategoryClassCode.APPOINTMENT]: '聘任材料',
  [PortfolioIdentityMaterialCategoryClassCode.BASIC]: '基本信息',
  [PortfolioIdentityMaterialCategoryClassCode.PROFILE]: '画像材料',
  [PortfolioIdentityMaterialCategoryClassCode.EXTERNAL]: '外部聘任材料',
  [PortfolioIdentityMaterialCategoryClassCode.INDUSTRY_MENTOR]: '产业导师材料',
  [PortfolioIdentityMaterialCategoryClassCode.ENTERPRISE_PART]: '企业兼职材料',
  [PortfolioIdentityMaterialCategoryClassCode.SKILL_MASTER]: '技能大师材料',
  [PortfolioIdentityMaterialCategoryClassCode.CRAFTSMAN]: '大国工匠材料',
  [PortfolioIdentityMaterialCategoryClassCode.TEACHING]: '教学材料',
  [PortfolioIdentityMaterialCategoryClassCode.RESEARCH]: '科研材料',
  [PortfolioIdentityMaterialCategoryClassCode.HONOR]: '荣誉材料',
  [PortfolioIdentityMaterialCategoryClassCode.ACHIEVEMENT]: '成果材料',
}
