/** 待办类型 - PortfolioTodoTypeEnum */
export enum PortfolioTodoTypeCode {
  ARCHIVE_RETURNED = 'ARCHIVE_RETURNED',
  ARCHIVE_PENDING_CONFIRM = 'ARCHIVE_PENDING_CONFIRM',
  ARCHIVE_DRAFT = 'ARCHIVE_DRAFT',
  CORRECTION_REJECTED = 'CORRECTION_REJECTED',
  CORRECTION_IN_PROGRESS = 'CORRECTION_IN_PROGRESS',
  GAP_PENDING = 'GAP_PENDING',
  GAP_RETURNED = 'GAP_RETURNED',
  EVALUATION_MATERIAL_CONFIRM = 'EVALUATION_MATERIAL_CONFIRM',
  EVALUATION_RETURNED_SUPPLEMENT = 'EVALUATION_RETURNED_SUPPLEMENT',
  DEVELOPMENT_PLAN_PENDING = 'DEVELOPMENT_PLAN_PENDING',
  DEVELOPMENT_PLAN_REVIEW = 'DEVELOPMENT_PLAN_REVIEW',
  DUAL_TEACHER_DRAFT = 'DUAL_TEACHER_DRAFT',
  DUAL_TEACHER_RETURNED = 'DUAL_TEACHER_RETURNED',
}

export const ALL_PORTFOLIO_TODO_TYPE_CODES: readonly PortfolioTodoTypeCode[] = [
  PortfolioTodoTypeCode.ARCHIVE_RETURNED,
  PortfolioTodoTypeCode.ARCHIVE_PENDING_CONFIRM,
  PortfolioTodoTypeCode.ARCHIVE_DRAFT,
  PortfolioTodoTypeCode.CORRECTION_REJECTED,
  PortfolioTodoTypeCode.CORRECTION_IN_PROGRESS,
  PortfolioTodoTypeCode.GAP_PENDING,
  PortfolioTodoTypeCode.GAP_RETURNED,
  PortfolioTodoTypeCode.EVALUATION_MATERIAL_CONFIRM,
  PortfolioTodoTypeCode.EVALUATION_RETURNED_SUPPLEMENT,
  PortfolioTodoTypeCode.DEVELOPMENT_PLAN_PENDING,
  PortfolioTodoTypeCode.DEVELOPMENT_PLAN_REVIEW,
  PortfolioTodoTypeCode.DUAL_TEACHER_DRAFT,
  PortfolioTodoTypeCode.DUAL_TEACHER_RETURNED,
]
